### ISSUE TITLE
Made new isetbio repository

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#1]
This cleared out a lot of space.  The master branch is what was the dev branch.  Wiki and gh-pages also moved over.  You will want to check out a clean copy of this as well as gh-pages and the wiki repository if you are using them.

Doing this cleared all history and issues.  They are still available in isetbio_v0.1.

There are some image files referred to by the wiki that were not in gh-pages.  These had to do with the coneAdapt documentation.  I will email Haomiao with a list.

I pulled out a bunch of large data files.  I will email Brian and Haomiao to see if we want any of them.

This should be good to go.  

I am not sure what will happen to people who we don't know who were using the old isetbio repository and who try to check something out.

**Comment by wandell** [comment]
Great stuff!

I will add a few little things here as we notice minor edits.  The one depressing thing is that the dreaded v_sceneRGB validation error is back.  But I am not going to think about that right now.

Here is the list

-2.  The setIsetbioUnitTestPreferencesTemplate discussion and use needs some tweaks.  We found it, ran it, and it worked fine for FastAll by default but not for the FullAll (of course).  We will think about how to help people like us.  We made some edits to the directions at the top.  The main thing that we need is a place where people know to get the validation data.  We took the data from the isetbio_v0.1 validationdata directory.

This doesn't seem like a hugely problematic issue right now because we are the only ones running the validation code.  Still ... 

Also, there should be a version of this function in the UnitTestToolbox directory that guides set up for any project.  Very useful tool!

-1.  We need to be a little more helpful to older isetbio users.  There aren't many of them, but they are our friends and wives.  I will think of some README annotation or email or something to send to Joyce, Emily, and maybe David Hoffman?  Maybe others.  (Less clear: Perhaps we should also add a warning message into the v0.1 so that people know there is a newer version, and an entry in the newer version to remind people that there is an older version.)  

0.  Getting rid of those larger files you listed in the mail is OK.  We should put at least some of them (which are useful from time to time) in a place where anyone can get them.  I will think about this.  Maybe a web-site we host here, and then a little pointer or link or something inside the ISETBIO code.

1.  The autrusseau analysis and data validation from the wavefront directory might get put in the computationaleyebrain repository as one of the projects rather than as fundamental isetbio stuff.  (The tif file in that analysis is kind of big.)

2.   I think the overall size is pretty good, though I am shocked at how big the one multispectral data file is.  Probably that could get re-written as single instead of double.  Or, let's just never mind.

3.  I thought we discussed isettools directories (color, cones, and so forth) migrating out to the main level.  Is that still on our list?  Or did you decide to leave it in the isettools directory.  Not important either.

Mainly ... GREAT JOB!

Brian and Haomiao

**Comment by DavidBrainard** [comment]
I put notes about where to go in the v0.1 repository README's and Wiki, as well as the index.html page there.  

I checked what happens if you try to pull into an old repository without doing anything.  You get a mess, many conflicts.  So at least our colleagues will know something is wrong.  How best to inform them that they should delete their old repository and check out a new one is less clear to me, since they are unlikely to look at the old (v0.1) repository where I did put a note.  

We could put something in the new repository that says to do this, I suppose.  Or email the ones we know about.

**Comment by DavidBrainard** [comment]
Our idea for isettools was not to move it up a level but to rename it to be called "code".  And to move the data out of that to the top level.  Moving the data involves fixing the path where routines look for it.  Not hard but a bit of search and replace work.

**Comment by DavidBrainard** [comment]
I moved several action items out of here into their own issues.

**Comment by npcottaris** [comment]
In response to Brian's  "Also, there should be a version of this function (setIsetbioUnitTestPreferencesTemplate) in the UnitTestToolbox directory that guides set up for any project. "

Under the UnitTestToolbox directory there is a folder named UnitTestTools. It contains a generic versions of
~~~
* UnitTestPreferencesTemplate.m
* ExecutiveValidationScriptTemplate.m
~~~ 
for use with any project. These were is a folder called UnitTestDemos, which is now renamed to UnitTestTools.

**Comment by DavidBrainard** [comment]
Thanks for adding the tools.  Does the documentation for the UnitTestToolbox point out that these are there?  If so, perhaps add.

**Comment by DavidBrainard** [comment]
I also added a note to the README in the new repository that tells how to handle the change.  It is the first thing you see on that page.  I'd say we leave the note there for a month or two and then remove.

**Comment by npcottaris** [comment]
The documentation for UnitTestToolbox (available at https://github.com/isetbio/UnitTestToolbox/wiki)
points to the location of these template files.

**Comment by DavidBrainard** [comment]
I think that the key things hanging from this issue have been handled and/or popped into their own separate issues.  Closing.
