### ISSUE TITLE
@osBiophys predictions against neural data

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#102]
Hello,

I added two validation scripts in the master branch. Both test the predictions of @osBiophys against neural data.

* `v_osBioPhysEyeMovements` script:  This script tests predictions against data recorded during a sequence of saccadic eye movements. During this sequence, the stimulus photon rate range was 0 - 80,000 photons/sec. The correspondence between model and data is good with an RMS error of 2.23 pA (see figure below).

![eyemovementstest](https://cloud.githubusercontent.com/assets/3444212/12306656/d0974c74-ba08-11e5-8cb2-04d7e8be907f.png)

* `v_osBioPhysStepResponses` script:  This script tests predictions against data recorded for 4 second long pulse stimuli of different amplitudes (7,864 - 1,123,999 photons/sec). Here the correspondence is not as good and progressively worsens as the stimulation amplitude increases (see figure below)

![pulsetests2](https://cloud.githubusercontent.com/assets/3444212/12930175/bd55f1dc-cf44-11e5-9f78-f4d36a7e67fc.png)

I am not sure if the failure is because of the model or because of the cell chosen for the comparison. 
The cell ID, as retrieved from the analyzed data file (isetbio archiva /resources/data/cones/stepExample) is 022211Ec07. 

Ideas, anyone?
Nicolas

**Comment by npcottaris** [comment]
Added a third validation script, `v_osBioPhysLightIncrementDecrementResponses`, which computes and  plots responses to light increment and light decrements at different pedestal levels.

It would be nice to have neural data to contrast these predictions against. Can we get some?

Attaching figure with model responses below:
![incrdecrresponses](https://cloud.githubusercontent.com/assets/3444212/12311001/11df25ee-ba22-11e5-8daf-296da23b80be.png)

**Comment by npcottaris** [comment]
Added fourth validation script `v_osBioPhysStepBriefFlashesResponses`, which tests the @osBiophys model prediction for brief light-incr. and light-dec. flashes on steps of different light levels. We have data (fits, actually) for light increment flashes, but not for light decrement flashes. Are there light decrement flash data that we can use here?

![incrdecrflashessummary](https://cloud.githubusercontent.com/assets/3444212/12330953/8aae132a-bab5-11e5-8999-2e544103bbfe.png)
![incrdecrflashes](https://cloud.githubusercontent.com/assets/3444212/12330963/93aca9be-bab5-11e5-850e-73ff0a287c05.png)

**Comment by fmrieke** [comment]
Thanks - this looks good.  We have not measure this for decrements (instead we have measured increment and decrement sensitivity at a few light levels - I’ll get you that data).  Also worth noting the fit to the data here is to collected data across cells - so we need not worry in this case about specifics idiosyncrasies of a particular cell.

Fred

**Comment by npcottaris** [comment]
Great, thanks!

**Comment by DavidBrainard** [comment]
Nicolas, while we await clarification on experimental data, could you do a pull request on the osvalidation branch and once it is pulled we can make that branch go away?

Best,

David

On Jan 13, 2016, at 11:19 PM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:


Added a third validation script, v_osBioPhysLightIncrementDecrementResponses, which computes and plots responses to light increment and light decrements at different pedestal levels.

It would be nice to have neural data to contrast these predictions against. Can we get some?

Attaching figure with model responses below:
[incrdecrresponses]<https://cloud.githubusercontent.com/assets/3444212/12311001/11df25ee-ba22-11e5-8daf-296da23b80be.png>

**Comment by npcottaris** [comment]
Done. Please approve.

M. T.

**Comment by DavidBrainard** [comment]
Just merged and pulled.  That was fun. G. C.,  in memorium.
.
On Jan 15, 2016, at 3:41 PM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:

Done. Please approve.

M. T.

**Comment by jamesgolden1** [comment]
In looking at v_osBioPhysStepResponses.m, it seems to me that the model predictions could be off because the range of the current output is limited. In the figure that Nicolas posted above from v_osBioPhysStepResponses, it is odd that the current cannot exceed 0 pA for any level of stimulus. After some debugging, it seems this limiting at 0 pA is actually a result of the constrained range of the output to a maximal change over time of ~86 pA. The removal of the offset before plotting causes this to appear as a limit at 0 pA.

I started hacking at the carefully chosen parameters of Fred's model, and found that within @osBioPhys/osCompute.m, the initial parameters for osAdaptSteadyState.m and osAdaptTemporal.m are determined by p = osInit on line 24 of osCompute.m. By altering the parameter from its initial value of 31682 to p.smax = 2000000 before the call to osAdaptSteadyState, the file outputs the below plot, which looks like a closer fit to the experimental data. The 86 pA limit is related to this, as p = osInit yields p.bgCur = 86.12. The arbitrary change of p.smax before osAdaptSteadyState changes all of the other p properties, and p.bgCur = 217.6. If we think of bgCur as the maximal range, this is enough to account for what is seen in the experimental data.

Fred details the biophysical model at http://isetbio.github.io/isetbio/cones/adaptation%20model%20-%20rieke.pdf and the smax parameters seems to control the creation rate of cGMP. Arbitrarily altering p.smax to make the model fit is an ugly way to do it, but I wanted to share the results and see what others thought. 

I did not push any changes to the repo, but the figure can be obtained by simply adding p.smax = 2000000 at line 43 of @osBioPhys/osCompute.m.

![v_osbiophysstep_output](https://cloud.githubusercontent.com/assets/8620201/12405847/741e2614-bdfc-11e5-9850-31fc76f6fa87.png)

**Comment by jamesgolden1** [comment]
My guess is that the appropriate way to deal with this issue is to provide the background isomerization rates from the experiment in the call to osCompute - is that information available in the mat file?


    client = RdtClient('isetbio');
    client.crp('resources/data/cones');
    [stepExample, stepExampleArtifact] = client.readArtifact('stepExample', 'type', 'mat');

stepExample.data:
             cellname: '022211Ec07'
           lightLevel: {1x7 cell}
                 Data: {1x7 cell}
              PS_Dark: {1x7 cell}
              PS_Step: {1x7 cell}
          MeanPS_Dark: [1x342 double]
                 Freq: [1x342 double]
      PS_LinearFilter: [1x711 double]
    Freq_LinearFilter: [1x711 double]
               DiffPS: [1x342 double]
     samplingInterval: 5.0000e-05

**Comment by fmrieke** [comment]
Sorry to be slow on this (getting slammed by teaching this month).  

This relates again to differences between cells I believe, as well as how we offset the data.  The outer segment current cannot exceed 0 pA - it is always negative (i.e. a current flowing into the outer segment), and reaches 0 only when all the transduction currents are close and the cone is saturated.  The recorded currents include the transduction current that we want to model plus an additional offset current from the inner segment (which is not light dependent).  That means that the recorded currents can exceed 0.  Typically what we will do is offset the currents by the current measured in saturating light (i.e. set that current to 0).  In the case of the data below that would mean offsetting by the peak of the response to the brightest step.  

The total outer segment current varies from cell to cell.  I think there are two possibilities to deal with this smoothly: (1) normalize everything to values between -1 and 0 (or between 0 and 1); (2) specific the cGMP concentration specifically for each cone in validation (which is how I have been doing it).  The maximal cyclase rate (p.smax) should be calculated automatically (or equivalently it could be set and the cGMP calculated).  But I think we need to be careful to make sure that the steady-state solutions of the differential equations are obeyed, so don’t want to alter parameters by hand individually.

Another issue this brings up is how we archive data. The .mat file with contents as below is in a format we have stored it for our own use.  I think we should use this opportunity to decide (at least for now) about a format that has all the pieces we need.

Fred

**Comment by DavidBrainard** [comment]
Thanks Nicolas, James, and Fred for this thread.  I think it would be helpful to set up a Skype to go over all this carefully together.

On Jan 18, 2016, at 11:20 PM, Fred Rieke <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry to be slow on this (getting slammed by teaching this month).

This relates again to differences between cells I believe, as well as how we offset the data. The outer segment current cannot exceed 0 pA - it is always negative (i.e. a current flowing into the outer segment), and reaches 0 only when all the transduction currents are close and the cone is saturated. The recorded currents include the transduction current that we want to model plus an additional offset current from the inner segment (which is not light dependent). That means that the recorded currents can exceed 0. Typically what we will do is offset the currents by the current measured in saturating light (i.e. set that current to 0). In the case of the data below that would mean offsetting by the peak of the response to the brightest step.

The total outer segment current varies from cell to cell. I think there are two possibilities to deal with this smoothly: (1) normalize everything to values between -1 and 0 (or between 0 and 1); (2) specific the cGMP concentration specifically for each cone in validation (which is how I have been doing it). The maximal cyclase rate (p.smax) should be calculated automatically (or equivalently it could be set and the cGMP calculated). But I think we need to be careful to make sure that the steady-state solutions of the differential equations are obeyed, so don’t want to alter parameters by hand individually.

Another issue this brings up is how we archive data. The .mat file with contents as below is in a format we have stored it for our own use. I think we should use this opportunity to decide (at least for now) about a format that has all the pieces we need.

Fred

**Comment by fmrieke** [comment]
I agree.  This week I could do that Thurs between 10:45 and 12:15 or between 2 and 3.  Fri between 11:30 and 1:15 would also work.  Next week is probably a bit more open if this week does not work.

Fred

**Comment by npcottaris** [comment]
I agree as well. Here is a list of things that I think we should address:

* Establish exemplar neural responses for  **light-increments & light-decrements** of various **amplitudes**, **durations**, presented on a different **background pedestals**.
  These data represent the most commonly encountered response and the model should be able to fit them accurately.

* Establish **valid ranges** for (a) pulse amplitudes, (b) pulse durations and (c) backgrounds for which the model predictions are adequately match those of the exemplar cells.

* Establish **ranges** for certain key **model parameters** which allow the model to predict neural responses that are less common than the exemplar responses, but still commonly encountered. Having such a range would allow one to conduct more accurate simulations of **mosaic outer segment responses** with realistic responses variances (beyond those produced by additive noise). This feature could be implemented by having a flag parameter in the @osBiohys model, which would control whether the generated object has the typical or the less typical (but still common) dynamics.

Nicolas

**Comment by fmrieke** [comment]
I can see how much of that we have (we certainly do not have complete data sets for all of the items below).  But a fundamental question here is how to handle variability in the cone responses (and this will come up when we think about ganglion cell models as well).  Some of that variability is likely real, but certainly a lot is a function of the state of the tissue during recordings.  We generally have assumed that the best recordings we get are likely the closest to how the cones are operating in vivo.  I don’t think we have any good way of estimating the variability of the actual cone responses in vivo because that variability is so confounded with what we introduce in the course of our experiments.  

The ideal thing to do - which is technically hard but not necessarily impossible - is to record all of the validation data from the same cell so we can test the ability of a model with fixed parameters to capture that.  What I had done instead in the old validation script was to try to fit largely to population data rather than individual cells.  

Fred

**Comment by DavidBrainard** [comment]
Fred’s times don’t work for me.

Maybe we could use Monday’s Skype for this topic?  I am also open next Tuesday (11:30-2:00 west coast time), next Thursday (9:00-2:00 west coast) and Friday (9:00-2:00 west coast).


On Jan 19, 2016, at 10:40 AM, Fred Rieke <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree. This week I could do that Thurs between 10:45 and 12:15 or between 2 and 3. Fri between 11:30 and 1:15 would also work. Next week is probably a bit more open if this week does not work.

Fred

**Comment by DavidBrainard** [comment]
This issue is getting long.  I am going to close it an reopen with an attempt at a fresh summary of the current status.
