### ISSUE TITLE
Matlab, libsvm, and mex compilation

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#104]
It turns out that various versions of Matlab rely on specific versions of xcode to compile mex files.

The release of El Capitan and new Xcode means that we need to change the mexopt.sh file in the Matlab.app/bin folder.  That mexopts.sh file includes a specific version number (in my case 10.7) of xcode.  I am told that it needed to be changed to version 10.11.

Now, having said that, I still don't have a working version.  The change to 10.11 did allow the train.mex file to compile.  But it reports an error.  So, at this moment, I have a fresh compile but not a working libsvm classifier.

Possilby, I have to compile other libraries.  I will keep looking into it.  But this error was obscure enough that James and I thought we better post the issue here to save some of you any trouble.

Here is the svm error message.

Invalid MEX-file '/Users/wandell/Github/isetbio/external/liblinear-2.01/matlab/train.mexmaci64':
dlopen(/Users/wandell/Github/isetbio/external/liblinear-2.01/matlab/train.mexmaci64, 6): Symbol not found:
_mexCallMATLABWithObject
  Referenced from: /Users/wandell/Github/isetbio/external/liblinear-2.01/matlab/train.mexmaci64
  Expected in: /Applications/MATLAB_R2013b.app/bin/maci64/libmex.dylib
 in /Users/wandell/Github/isetbio/external/liblinear-2.01/matlab/train.mexmaci64

Error in svmClassifyAcc (line 92)
            svmStruct = train(labels(trainIndx),trainData,opts);

**Comment by DavidBrainard** [comment]
Nicolas has considerable experience with mex compilation magic, as does Ben.  Perhaps one or the other or both can help.

While we’re on svm, In another project I recently discovered that which algorithm I picked for a linear SVM (with Matlab’s svm, not libsvm) made a substantial difference in the classification performance that I got.  And that the different algorithms took quite different amounts of time.  I didn’t compare to libsvm.

On Jan 15, 2016, at 8:02 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


It turns out that various versions of Matlab rely on specific versions of xcode to compile mex files.

The release of El Capitan and new Xcode means that we need to change the mexopt.sh file in the Matlab.app/bin folder. That mexopts.sh file includes a specific version number (in my case 10.7) of xcode. I am told that it needed to be changed to version 10.11.

Now, having said that, I still don't have a working version. The change to 10.11 did allow the train.mex file to compile. But it reports an error. So, at this moment, I have a fresh compile but not a working libsvm classifier.

Possilby, I have to compile other libraries. I will keep looking into it. But this error was obscure enough that James and I thought we better post the issue here to save some of you any trouble.

Here is the svm error message.

Invalid MEX-file '/Users/wandell/Github/isetbio/external/liblinear-2.01/matlab/train.mexmaci64':
dlopen(/Users/wandell/Github/isetbio/external/liblinear-2.01/matlab/train.mexmaci64, 6): Symbol not found:
_mexCallMATLABWithObject
Referenced from: /Users/wandell/Github/isetbio/external/liblinear-2.01/matlab/train.mexmaci64
Expected in: /Applications/MATLAB_R2013b.app/bin/maci64/libmex.dylib
in /Users/wandell/Github/isetbio/external/liblinear-2.01/matlab/train.mexmaci64

Error in svmClassifyAcc (line 92)
svmStruct = train(labels(trainIndx),trainData,opts);

**Comment by npcottaris** [comment]
Brian: what is the top-level matlab script that you are running?
i.e., the one that calls svmClassifyAcc in line 92.

N.

**Comment by npcottaris** [comment]
### Instructions to seafarers

(1) I pushed a mexopts.sh file in `.../isetbio/external/liblinear-2.01/matlab`  (main branch).
~~~
git pull to get it.
~~~


(2) Using terminal:
~~~
cd .../isetbio/external/liblinear-2.01
make clean   (this will clean the existing mex files in the matlab subdirectory)
make
~~~

On my ElCapitan OS X, with xCode 7.2 (7C68), this generates 6 warnings.

(3) Using Matlab's command window:
~~~
cd .../isetbio/external/liblinear-2.01/matlab
make
~~~
I get one warning.

I do not know the top-level program that you are using, so I am not able to verify that the produced mex file will work for you.

Nicolas

**Comment by jamesgolden1** [comment]
It is from HLColorOpponentGabor/tutorials/t_colorGaborDetection.m.

**Comment by wandell** [comment]
On the rgc brarnch.

**Comment by npcottaris** [comment]
OK. In addition to adding the `mexopts.sh`, I also had to change the MATLABDIR  from 
`/usr/local/matlab`  
to 
`/Applications/MATLAB_R2015b.app`
in the Makefile located in `...isetbio/external/liblinear-2.01/matlab` 

This was all done in the rgc branch.
Then 
make clean; make.

I pushed these changes plus the newly generated mexmaci64 files, back to the rgc branch.
The tutorial run without crashing when calling `svmClassifyAcc` in line 246.
Can you try it?

**Comment by jamesgolden1** [comment]
It runs for me as well, thank you Nicolas. I will wait for Brian to give
the final verdict.

**Comment by npcottaris** [comment]
OK. Good.  Got to run now...
Brian, please let me know if this is not working for you.

Cheers,
Nicolas

**Comment by wandell** [comment]
In my case, I am running Matlab 2013b.  Doing the edit to the Makefile did in fact make my instance run properly.  So that's good.

The isetbio repository, however, contains the *.mexmaci64 files that I think Nicolas computed on Matlab 2015b.  Those do not run on my version.  So, probably shouldn't have these mex files in the repository.  Either that, or we need some plan for managing these damn mex files with different versions.  Sigh.

**Comment by npcottaris** [comment]
Brian, did you try to compile new mexmaci64 files on your machine?

In ...isetbio/external/liblinear-2.01/matlab, from within Terminal.app do
~~~
make clean 
make
~~~

**Comment by wandell** [comment]
Yes, I compiled and it all runs through fine.  The question is really how do we handle the different versions of the mex files.  I hate this aspect of Matlab.

**Comment by npcottaris** [comment]
We need to have a smarter Makefile which detects the OSX version and perhaps the installed Xcode version and selects one from a set of mexopts.sh files, which we would have to provide and which should cover a range of systems. We would probably need to establish the minimum requirements like OS X 10.9, Matlab 2013b etc.

N.

**Comment by DavidBrainard** [comment]
This seems obsolete.  In general we want to as far away from mex files and compiled C code as we can.  There is a new issue about whether we can deep six libsvm and liblinear.
