### ISSUE TITLE
Retinal ganglion cell mosaic code organization

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#106]
James and I would like your thoughts on this very brief description of the [class organization](https://github.com/isetbio/isetbio/wiki/Inner-retina) for the ganglion cell mosaics and inner retina.

This is close to what we are doing now, but simpler.  It deviates in some small technical ways that are important to James (and me).  Let us know your questions or comments.

Thanks,

**Comment by fmrieke** [comment]
This looks good to me.  Only thing I saw was that I would want to make sure that the input specification is general - e.g. could be stimulus, outer segment object, potentially bipolar object, … .  Likewise a place I could see someone customizing things is through mosaicCreate - so standardizing input and output from that stage would help make clear what someone needed to do to insert their own model.

Fred

**Comment by npcottaris** [comment]
This looks good to me, at least in this stage. 

One thing that you may consider changing, is avoiding passing the stimulus to each mosaic's compute method, as this may increase the computation time due to communication overhead. That, of course, depends on how large the stimulus is and how many mosaics are to be computed.

In any case, this is how I would do it.
~~~
   ir.setStimulus(stimulus);
   for ii=1:length(ir.mosaics)
       ir.mosaicCompute(ii);
   end
~~~
where the `@ir` class definition has a public property named `stimulus` and a `setStimulus` method, which does the following:

~~~
function setStimulus(self, stimulus)
   % validate the structure of the passed stimulus here 
   if (stimulusIsNotValid)
   	   error('Stimulus does not have a valid structure');
   end

   % stimulus is valid, so set it (once only)
   self.stimulus = stimulus;
end
~~~

and the mosaic's compute method is defined as
~~~
function mosaicCompute((ir, k)
   % access the ir.stimulus by reference, since the ir class inherits from handle
   % do stuff with ir.stimulus and mosaic{k}
end
~~~

**Comment by jamesgolden1** [comment]
Fred, that is a good point - currently the mosaic and inner retina computations can take as input either a dynamic scene (x, y, t, RGB) or an outer segment object, although the computations that take the outer segment current to RGC output are more or less a placeholder at this point. A bipolar/subunit model is also something that I will incorporate.

Nicolas, the computations do require passing the stimulus to the compute function for each mosaic. My sense from the outersegment object was that we did not want to store copies of previously computed objects. At present, each mosaic is composed of all RGCs of a given type, so typically there are five mosaics corresponding to ON Parasol, OFF Parasol, ON Midget, OFF Midget and Small Bistratified cells. I haven't seen performance issues connected to the stimulus passing, but this could be due to my use of relatively small stimuli for testing purposes. The main bottleneck in computation time so far seems to be the array operations for computing spikes over the whole mosaic with the coupled GLM model.

I wil post a few slides later today that summarize the current architecture of the IR/RGCLayer object and mosaic object in anticipation of the discussion Wednesday morning.

**Comment by npcottaris** [comment]
Re: I haven't seen performance issues connected to the stimulus passing, but this could be due to my use of relatively small stimuli for testing purposes.

Yes, I was thinking about our simulations, where we have 20x20 outer segment  mosaics and temporal sequences with millions of data points, due to simulations of saccadic eye scans over multiple scenes.

**Comment by npcottaris** [comment]
After several tests of passing the stimulus either by value or by reference, I concluded that there is no benefit of using the the by-reference paradigm, even for stimuli of 400 cones x 1,000,000 time points. 
Therefore, you can ignore my previous suggestion.

**Comment by jamesgolden1** [comment]
Nicolas, thanks for testing this, good to know.

**Comment by benjamin-heasly** [comment]
LGTM2!  I had two thoughts.

---

Following on @fmrieke, about extending the code.

I am wondering how the code would process the strings passed to `mosaicCreate('parasol','LN');`.  Would there be a switch statement or similar that checks the values and enacts some appropriate logic?

If that's the case, then I think someone who wanted to extend the code would have to go in and modify `mosaicCreate()` itself, by adding a new case to the switch.  I think this could be a barrier for some users.  It also might become difficult to reconcile various changes that people make.  For example, two people might want to add a case for "ultimate-mosaic", but they might want to implement it differently.

One possible alternative would be to let `mosaicCreate()` accept objects instead of strings.  As Fred mentioned, this would require us to standardize what Mosaics and ComputationalModels look like.  But once standardized, users could pass in any objects they wanted.  The could pass in a standard object defined in isetbio, perhaps ieParasolMosaic, or some custom object they are hacking on, perhaps MyUltimateMosaic. 

In code, maybe it would look something like this:

```
% default object
ir = ieInnerRetina();

% use official isetbio code
ir.mosaicCreate(ieParasolMosaic(), ieLnModel());
ir.mosaicCreate(ieMidgetMosaic(), ieCoupledGlmModel());

% compare my custom idea to your custom idea
ir.mosaicCreate(MyUltimateMosaic(), MyUltimateModel());
ir.mosaicCreate(YourUltimateMosaic(), YourUltimateModel());
```

---

Also, I have a guess about the performance question.

My understanding is that Matlab has pass-by-value semantics for non-handle arguments.  But, I think the actual implementation avoids making a copy of any arguments until one is actually modified (aka "copy-on-write").  So if `compute(stimulus)` never modifies the `stimulus`, I think the performance should be the same as pass-by-reference.  Is that a reasonable way to account for what you're seeing @npcottaris ?

**Comment by npcottaris** [comment]
My version of `compute(stimulus)` does not modify the stimulus, so yes, this is a reasonable way to account for the results.
The same should be true in the actual implementation, i.e, the stimulus should not be modified.

**Comment by wandell** [comment]
James and I have reorganized the classes and directories in the RGC branch in response to these comments and some additional thoughts.  This issue is no longer needed.
