### ISSUE TITLE
Design Ideas / Questions / Pictures

### ISSUE THREAD

**Issue by benjamin-heasly** [isetbio/isetbio#111]
Hi everyone,

I put together a document that outlines some of the design issues I've heard the group talking about, plus some of my ow thoughts: [ISETBIO Design and Questions](https://drive.google.com/open?id=1B6s3y4OIQKouiK73AHWrGpWCFKeXLGiwnzfqLAFbE4c).

David and I have talked this over and added some of our own comments.

Would like to know what you all think, too.  The Google should allow you to make comments and edits.

Thanks!

Ben

**Comment by jamesgolden1** [comment]
Ben, thank you for this analysis, it really helped clarify some of the ideas about the architecture for me. In terms of linking compute objects to one another (e.g., scene => oi => sensor => outer segment) and whether we should use a chain or DAG. 

I would like to take a rhetorical position against the DAG approach for a moment. My primary worry is that with certain implementations of an eyeball/container object (that holds the compute objects), we could end up with an architecture that is too complex and intimidating for new users. If we consider a tutorial function like t_os that could be used to compare Fred's two models for cone current computation, currently it effectively implements a type of tree structure. A sensor is created, and the two different outer segment objects are created with each taking the sensor as input. The way this is constructed, we are relying on the user to know not to change properties of the sensor so that the two outer segment currents can be compared.

As we've discussed, explicitly implementing a container object as a DAG of compute objects would prevent the user from even having the opportunity to alter the properties of the sensor and ruin the comparison. The cost to adding a container object is added complexity, and I think that is worth it as long as we hide the complexity from the user. As Ben described in the google doc, we could build the container such that it would be completely independent from the compute objects. As long as we keep the container operations in the background after some sort of initialization, I agree that a container is the way to go.

**Comment by benjamin-heasly** [comment]
Thanks James :)

Can I try to echo back part of what what you're saying, just to to get on the same page?

Using a container to manage the compute objects could be nice, and might even improve tutorials like [t_os](https://github.com/isetbio/isetbio/blob/master/tutorials/outersegment/t_os.m) by making it easier for users to do the right thing / harder to do the wrong thing.

This seems true for a container that manages a relatively simple graph, like a tree.  So a tree-container might be a friendly container.

But a DAG-container might be more intimidating and not so friendly, especially to new folks.

If that's a fair echo, then I agree!

When you put it this way, it makes me think that we could start with a tree-container.  Then later, if we are in need and feeling bold, we could try writing a separate DAG-container.  The two containers would be independent from each other and from the ComputeObjects, so nothing would need to break at that point.

**Comment by fmrieke** [comment]
I put a comment on the document about this - but let me pull it out too.  I think we should think about this architecture in terms of levels of interaction a user has with the code - particularly in the form of a GUI.  If the architecture is intuitive, it seems we could basically expose it as a GUI.  This is a somewhat different view as it would put any kind of container object front and center.  What I had in mind there was that many users may want to run a computation using preset parameters/compute objects and just specify the connections between them.  That seems like either specifying the links in the tree or the elements in the container depending on the architecture.  I think if the container contains things like how parameter calls upstream are resolved it needs to be visible.  

Fred

**Comment by DavidBrainard** [comment]
Closing.  Not currently relevant.
