### ISSUE TITLE
Identity xform in os object

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#117]
It looks like the identity method in the os object provides RGB values from the scene, not the isomerization rates of the cones, as far as Xiaomao can tell.  That is, it both takes the scene as input and gives RGB values as output.

We understand that this was there as a way to plug extant rgc models into the os output, but is is causing us confusion.

Any objectsion if we name that functionality something else (such as 'scenergbhack') and write a true identity method that gives us the isomerizations out the back end of the os object?  This will require some changes in rgc code, we imagine.

**Comment by jamesgolden1** [comment]
My impression was that passing an object named "os" to the inner retina rgc object was a good thing. If we switch osIdentity to something called scene, then I think we should just squash the idea completely, and I will change the rgc code to accept the scene structure directly.

However, it seems osIdentity was only a good thing insofar as it was not known that it didn't store the isomerizations data. Would it be possible to augment osIdentity with a 'photons' or 'photon rate' field from the sensor? 

That being said, I am fine with squashing osIdentity if in its current state it makes things worse.

If we get rid of osIdentity, do you think this is worth a branch, or will you implement it directly in the master branch?

**Comment by fmrieke** [comment]
My take would be to augment osidentity so it inherits the the isomerization data.  I think this is also consistent with a future format where the rgc object could reach up to os, which could then reach back to scene (with a “predecessor” field).  

Fred

**Comment by wandell** [comment]
I hope this helps.

There is a need to go straight to RGC from scene RGB because that is what the coupled GLM does.  So, we named osIdentity as the method that does not transform the display at all, but just delivers the RGB as the model requires.

There should be another outer segment transform that converts to isomerizations.

There is another one that linearly filters the isomerizations.

There is another one that implements Rieke.

There could be others.

Brian




Stanford
Sent from mobile device

On Apr 1, 2016, at 5:12 PM, Fred Rieke <notifications@github.com<mailto:notifications@github.com>> wrote:

My take would be to augment osidentity so it inherits the the isomerization data. I think this is also consistent with a future format where the rgc object could reach up to os, which could then reach back to scene (with a "predecessor" field).

Fred

> On Apr 1, 2016, at 2:04 PM, jamesgolden1 <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> My impression was that passing an object named "os" to the inner retina rgc object was a good thing. If we switch osIdentity to something called scene, then I think we should just squash the idea completely, and I will change the rgc code to accept the scene structure directly.
>
> However, it seems osIdentity was only a good thing insofar as it was not known that it didn't store the isomerizations data. Would it be possible to augment osIdentity with a 'photons' or 'photon rate' field from the sensor?
>
> That being said, I am fine with squashing osIdentity if in its current state it makes things worse.
>
> If we get rid of osIdentity, do you think this is worth a branch, or will you implement it directly in the master branch?
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/117#issuecomment-204565317>


-

**Comment by npcottaris** [comment]
In this case, it looks to me that the naming scheme is misleading. All of ISETBIO objects are elements in a cascade operation and they have a clearly defined position in that cascade. Therefore the word identity In any of these objects should imply that it delivers its actual input, in the present case, the isomerizations.

I think that if we need an object that delivers the signal that exists farther than 1 processing stage back,  we should name it something like osPassThrough('origin', stimulusRGB)  (or something along those lines).

Just my 2 cents...

Nicolas

On Apr 2, 2016, at 12:55 AM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:

I hope this helps.

There is a need to go straight to RGC from scene RGB because that is what the coupled GLM does. So, we named osIdentity as the method that does not transform the display at all, but just delivers the RGB as the model requires.

There should be another outer segment transform that converts to isomerizations.

There is another one that linearly filters the isomerizations.

There is another one that implements Rieke.

There could be others.

Brian




Stanford
Sent from mobile device

On Apr 1, 2016, at 5:12 PM, Fred Rieke <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

My take would be to augment osidentity so it inherits the the isomerization data. I think this is also consistent with a future format where the rgc object could reach up to os, which could then reach back to scene (with a "predecessor" field).

Fred

> On Apr 1, 2016, at 2:04 PM, jamesgolden1 <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:
>
> My impression was that passing an object named "os" to the inner retina rgc object was a good thing. If we switch osIdentity to something called scene, then I think we should just squash the idea completely, and I will change the rgc code to accept the scene structure directly.
>
> However, it seems osIdentity was only a good thing insofar as it was not known that it didn't store the isomerizations data. Would it be possible to augment osIdentity with a 'photons' or 'photon rate' field from the sensor?
>
> That being said, I am fine with squashing osIdentity if in its current state it makes things worse.
>
> If we get rid of osIdentity, do you think this is worth a branch, or will you implement it directly in the master branch?
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/117#issuecomment-204565317>


-
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/isetbio/isetbio/issues/117#issuecomment-204567127>

-

**Comment by jamesgolden1** [comment]
I pushed some changes that converted osIdentity to store the sensor's 'photon rate' instead of RGB data, and I created a new outer segment object called osDisplayRGB to store the RGB data. I am working on catching previous uses of osIdentity and converting them, so there could be some small problems lurking in the RGC tutorials.

**Comment by wandell** [comment]
With James.  He thinks this is now implemented as osIdentity.  The input to the RGC model is called osDisplayRGB as above.
