### ISSUE TITLE
Lens plot from oi window can get confused

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#130]
If there are two OI's in a window and I've selected the first one and then do a lens plot, I still seem to get the lens from the second one.  See IBIOColorDetect/tutorials/t_colorGaborScene for an example of this behavior.

**Comment by hjiang36** [comment]
Thanks for pointing it out.

The reason for this error is because Lens now becomes a handle class.
As a consequence, lens is always passed by reference (though oi is passed by value). Thus, when you change the lens parameters for the new OI, the parameter of lens in old OI is also changed (they basically share the lens).

To fix this undesired behavior, I committed a fix to make Lens a value class. This should solve your problem.

If this change breaks some other stuffs, let me know.

HJ
