### ISSUE TITLE
Absorptions versus isomerizations

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#137]
This is a small terminology thing, unless the calculation isn't doing what I think it is.

My understanding is that photopigment can absorb a quantum without isomerizing, and that that the quantity we want to compute as the mosaic response is isomerizations, not absorptions.  I suspect we are in fact correctly computing isomerizations, because there is an explicit photopigment quantum efficiency parameter in the cone calculations, or at least there was last time I was in it (pre coneMosaic era).

The name given in the mosaic object, however, is absorptions, which I find a little confusing.  The name is not a huge deal.  It is probably important to make sure we are in fact computing isomerizations.

**Comment by fmrieke** [comment]
There should indeed be a factor of 0.67 to account for the quantum efficiency of photopigment activation.  That might get absorbed into the definition of the collecting area as well. 

Fred

**Comment by DavidBrainard** [comment]
I think it is explicitly there, called cone peak efficiency in the window that comes up when you examine a cone mosaic object, and that it is just the name given to the output and used in specifying plots that is a little confusing.

**Comment by wandell** [comment]
When I return (am at a conference), I will discuss this and some other things with you and @hjiang36 .  

1.  The distinction between absorptions and isomerizations is pretty subtle, but interesting.  Do we want the code to reflect those two possible outcomes?  If so, do we want to force people to specify which they want?  As per the discussion, isomerizations are really what interest us.  We have been using the word absorption rather than isomerization.  Changing that parameter name and explaining will be kind of a pain, but this is definitely the time.

2.  Related - when we create the 'photoPigment' object, we read in a file called coneAbsorbance.mat.  But the data in that file need to be 10^.values to become absorbance.  I am wondering whether we should change the data, or the name of the file, or there is some reason to just live with the current situation.

3.  Also related - the current spatial parameterization in the photoPigment object has both the sample spacing between the cones and a fraction of the surface area that is absorbing.  In this way, you can account for the fact that, say, the cones are separated by 2.2 um but the collecting area of the cone inner segment is only 1.8um.  Do we want to keep that?

At the moment, the names of the two parameters are cone size and pd size, which are legacy names.  @hjiang36 and I will look into whether we want to change the parameter names and how much of a pain that will be. 

P.S.  Am in DC.  It is midnight.  There is a thunderstorm and the temperature is 90 degrees.  Why does anyone want a job where they have to live here?  Can I go home now?

**Comment by DavidBrainard** [comment]
Sounds good.  I have some opinions about some of these matters and would like to review with you guys.  Let me know when you are back.

**Comment by DavidBrainard** [comment]
I think we have reached asymptote on this one, and that "isomerizations" and "absorptions" are now being used as synonyms in our code and documentation.  I can't bring myself to call them "absorptions" but can live with "absorptions" when I see it.  Closing on the grounds that we have bigger fish to fry.
