### ISSUE TITLE
Do we allow in the statistics toolbox for ISETBIO?

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#141]
One method of coneMosaicHex (resampleGrid) makes use of pdist2, which is part of the statistics toolbox.

I implemented my own version of the functionality of pdist2 that I needed as a mex file. This is found in the pseudo hex branch under external/pdist2. 

As a temporary solution, this stats toolbox independent solution, is enabled in line 53 of the constructor of coneMosaicHex, as follows:
`obj.useStatsToolboxPdist2 = false;`

I run a number of benchmarks. On average my version is about 1.6 times slower than Matlab's version. I think we can live with this if we want to avoid the Stats toolbox. The implementation that Brian found in matlab central is 10 times slower, and it ever run out of memory for some mosaics.

Nicolas

**Comment by wandell** [comment]
Maybe we should take a straw vote, but I think we are probably all in favor of permitting the stats toolbox for ISETBIO.  For the record, my reasoning is this.

I limited to the Image Toolbox in ISET because the toolboxes are expensive, I didn't have a big need for the stats, and many of the ISET customers were already paying a lot for Matlab.  So, it was a matter of the market.  

On the academic side, and I think ISETBIO is entirely academic, the stats toolbox is widely available and usually just included.  So the main reason for avoiding it is irrelevant.

Furthermore, I spent some time looking through the functions in the toolbox (which is listed as Statistics and Machine Learning).  It has lots of functions that are of value to us; there is no real point in re-writing, particularly since we won't do it as well as they do.

Finally, for a brief couple of months I was thinking there was some value in keeping major parts of ISET and ISETBIO aligned.  But this is not even close to possible any more, they have diverged enormously. (We might even consider a new name).  So, that reason for matching is also eliminated.

Anyway, my vote is let's allow in the stats and machine learning toolbox.

**Comment by fmrieke** [comment]
I think Brian’s rationale here is right.  For our modeling work, the stats toolbox is the most useful among all the options.  We no longer pay by toolbox, but when we did we always got that one and few others.  So I’d vote for permitting it.

Fred

**Comment by DavidBrainard** [comment]
I think I already weighed in in favor of stats, but without any explanation.

Brian’s message captures my thinking well, however.  Toolboxes I think we need are signal, image, stats, and probably optimization.

I do think we ought to make an explicit list of dependencies and try hard to develop within it, expanding with discussion as necessary.  Ben’s new ToolboxHub will help a lot with this, as we should be soon to explicitly state our dependencies in a JSON file and put Matlab into a configuration that has all and only those dependencies with a single command along the lines of “tbHubDeploy(‘isetbio’)”  More on this in a week or so.

The one thing that will remain a bit difficult to manage will be Matlab version dependencies, but I think we can do this manually as we discover them, without too much hassle.

**Comment by npcottaris** [comment]
Totally agree. Stats & Machine learning is a very useful toolbox. 

I will keep support for the pdist2 mex alternative in the pseudo hex branch, which we should consider experimental. The hexdensity branch, which we will use to finalize the mosaic/density stuff,  does not have that option as it was formed earlier.

Nicolas

**Comment by wandell** [comment]
Agreed, then, and closing.
