### ISSUE TITLE
Merging hexdensity into master?

### ISSUE THREAD

**Issue by jamesgolden1** [isetbio/isetbio#146]
Has the time come to merge the hexdensity branch into the master branch? I could start this process, but I wanted to check if the merge should wait until the validation runs in the master branch have been ironed out.

**Comment by DavidBrainard** [comment]
I would recommend making a branch or tag of the current master branch and then going ahead and doing the merge.  Our goal is to have the validations working in the merged branch anyway.  But it would be nice to have the current master branch stashed, so that we can easily compare the performance of the two if need to.

**Comment by wandell** [comment]
@jamesgolden1 and I did the merge of hexdensity into master.
Please start using master and branching from there.  We think hexdensity is now a dead branch.
