### ISSUE TITLE
sensorDemosaicCones

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#16]
I've had a read through and done some testing on sensorDemosaicCones.

It was giving slightly different answers than the griddata version I wrote.  I tracked this down to two places where x and y were being treated differently in the two pieces of code.  I rewrote the code in sensorDemosaicCones to match what I had done previously, with fairly extensive comments and the old code still there but commented out (it is two lines, one the call to meshgrid and one the call to ind2sub.)  You might think the two reversals in x and y would simply cancel each other, but this is not exactly true.  I think the way I left it matches what the documentation says to do, but I am not 100% confident and could be convinced otherwise.  Haomiao, perhaps you can take a careful look over this.

The other buglet is that the code was scaling the LMS values as would be needed to make the cone sensitivities have a peak of unity, which is not how the quantal efficiencies are scaled.  This seems like the right ideas, but I think the scale factors should be computed in with the cone sensitivities in energy rather than quantal units.  I added a conversion to energy units.  Again commented and again worth a careful read over.

Finally, I added a second return argument, which is the demosaic'd isomerizations array.  Sometimes one wants this rather than just sRGB.  I did not pass this through any scaling or fixing for dichromats, as I think the raw form is most useful when this array is wanted.

I am still getting a difference in the sRGB images I create outside isetbio and with the one created in this routine, which I have yet to track down.  It is mysterious because in many other instances the two ways of doing it agree well.  But I think this is as likely a bug in my test code as in sensorDemosaicCones.

**Comment by hjiang36** [comment]
Thanks a lot, David.

As for griddata issue, you are exactly right. I got confused there when I wrote the code. Now, your code and comments explain clearly to me.

Also, I agree that we should scale in energy units. In the future, we might want to have functions that do transformation on LMS values directly, instead of scaled version.

Another issue is that the photon noise effect is so large here. If using noise free sensor data, we get a blurred version of input rgb image. But with noise, even if the scene is quite bright (say 100 cd/m^2), the noise is still very visible. Not sure if cone adaptation will make it better or we should try some other methods.

I'll remove my code (you've commented out) and update a little the comments in that function.

Thanks

**Comment by DavidBrainard** [comment]
I tracked down why my sRGB renderings differed in this case.  It isn't a problem in the demosaicing.  Here is what causes it.

% The exact order of clipping and scaling in the conversion from
% XYZ to sRGB matters in some cases.  ISETBIO scales in XYZ by
% the maximum Y value, then clips negative XYZ values, then converts
% to SRGB primaries, and then clips to 0-1.  PTB does not touch the
% XYZ values normally, and can either scale to max of 1 in SRGB primary
% or clip, depending on how you call SRGBGammaCorrect.

I am not sure what the official right way to do this is.  I am leaving it alone for now, but will add a note to the validation script that compares ISETBIO and PTB conversions to sRGB.
