### ISSUE TITLE
cone mosaic visualization

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#161]
The master branch is now running through the validations.  That's great!  

@jamesgolden1 and I made a few little changes to get ready for visualizations in the cone mosaic window, merged again, and deleted the osvalidation branch.

Next we hope to put @npcottaris visualizations of the hex mosaic into the cone mosaic window.  Towards this goal, there is a new coneMosaicHex.plot function that contains a place holder for the hex visualization.  We are having trouble, however.

When we create a hex cone mosaic, we succeed at the visualization using @npcottaris visualizationGrid(obj) call. But when we call the same basic routine on the axis within the cone mosaic window, (see line 65 of coneMosaicHex.plot) , bad things happen to our axis.  Specifically, the patch() drawing does something we don't understand to the x- and y-axis scales and the whole axis shrinks to a tiny dot.

This is a plea for help to @npcottaris to look into what we need to do to render the hex array as a patch inside the cone mosaic window's image axis.  We tried changing a whole variety of axis parameters today, got nowhere, and thus are creating this issue.  We need the help of an expert!

**Comment by npcottaris** [comment]
Thanks for the complements !

This issue is now fixed by resetting the axes (line 58). 

![window](https://cloud.githubusercontent.com/assets/3444212/18849970/726813fc-8403-11e6-9e1a-1c0e39ace948.png)

**Comment by wandell** [comment]
The visualization of the mosaic in our GUI window is slow, and creates problems when we resize the window.  Not sure why.

As a short term fix, we only put up the rectangular form for the cone mosaic case.  Interestingly, the hexagonal case for the mean absorptions seems OK.  So, we are hopeful that we will be able to sort this out.

To visualize the cone mosaic in all its glorious color, we still have the Plot | Mosaic | Cone Mosaic option.  @jamesgolden1 and I will have a god at this again next week. 

We also patched up some big inefficiencies while hacking on this issue.

**Comment by npcottaris** [comment]
I agree that there is something going on with line plotting in the comeMosaicWindow. 

(1) It is much slower than in a figure with no GUI controls.
(2) The lines are not smooth like in the figure with no GUI controls.

The rendering is sped up a bit by setting the patch line style to 'none'. Did that change already.
Another way to significantly increase the rendering speed is to set the dAngle to 60 (from 15) in line 60, which results in plotting hexagons instead of circles.

**Comment by npcottaris** [comment]
Hi Brian,

I tried several different ways to speed up the rendering speed. After several hours of $&%^#$&#$^^&$(!#@  I found what the problem was. The coneMosaicWindow's Renderer was by default set to 'painters'. I changed it to 'OpenGL' and performance is now much better, on par with the separate window.

Please try it and let me know if this works for you as well.

Nicolas

**Comment by wandell** [comment]
Wonderful!   Amazing that you found the key parameter. (It is running well on my Mac at home). Remembering about OpenGL as a painter will surely matter over the years.

Given your experience, I changed the Renderer in the sceneWindow and the oiWindow and the mosaicWindow, too.  We should remain alert with this change.  But let's try for now.
