### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#17]
I’ve been playing a little with some of the isetbio tutorials (and trying to keep up with the many emails).  One general issue I wanted to bring up was units. How much work would it be to specify units in the relevant structures/objects?  For example, there could be a units field associated with every data field.  I think in the long run this could be very helpful as other users start to use things.

**Comment by DavidBrainard** [comment]
Brian can say more about this, but here is my understanding.

We should think of those isetbio structs as objects, that is we're not really supposed to be looking at the structure (although I confess, I do it too).  Thus the point of interface is the sets and gets.  These generally allow you to say what units you want the answer in with an additional argument.  Thus you can code in a way that makes the units explicit by always putting in that argument.

There are default units for everything, and (I think) these are what is stored in the structures.  These units are counted on by the set and get code.  I do think it would be useful to have a list of these somewhere, either on the wiki or in the help for each set/get function.  And also a handy reference of the unit strings that are used to specify different units in the sets and gets.  That would go a long way to making the units clearer.

**Comment by DavidBrainard** [comment]
While we're on this general topic, another thing that would be great to have a cheat sheet for is what the general syntax is for optional args.  Sometimes it seems to be extra passed strings or values that can be excepted, in other cases there is a parameters structure passed from whose fields optional args are pulled.  There may even be string/value pairs lurking.  I am not sure.

I would particularly like to have us decide on and write down a style we'll adhere to for new stuff, even if we don't immediately change older stuff to match.

**Comment by npcottaris** [comment]
One solution for many of these issues would be to have wrapper full-fledged Matlab objects that will manage access to the existing core isetbio objects, which are actually structs. In this way some of us could still use isetbio the old way as there would be no modifications in the existing code, whereas new  users would be encouraged to access isetbio via the new objects. This would allow safer access to isetbio data (with some data being private, I.e. inaccessible to users, other being public but read-only and yet other being public read-write ). This solution would also enforce a consistent coding style using a clean syntax of key/value pairs input arguments which would help new users. Moreover the Dependent properties mechanism of Matlab objects would solve some of the issues that we have now, for example setting the angular size of a scene would automatically set its width, instead of the user having to set both. An argument parser in all methods that access data would exist which would require the user to either specify the desired units or pass a default flag in which case the default units would be used.

**Comment by fmrieke** [comment]
This sounds like a good solution to me.  I think being explicit about having someone set (and be able to check) the units would be quite helpful.  

Fred

**Comment by wandell** [comment]
CLAASES
The RGC objects are handled with sets/gets this way.  And I think our recent conversations suggested that we want to force all new classes to have a minimal set of methods that include sets/gets/plot in addition to the constructor.  

And our last conversation taught me that we will use key/value pairs and that Matlab has a parser that will be our standard for interpreting the calling arguments.

UNITS
The issue of default units (and documenting them both in the code and in the manual) is important and separate. The current method uses a function that accepts a string for units (e.g., 'microns') and assumes that the structure contains a field in a standard unit (in this case meters).  The data are converted.  There is an attempt to make everything in standard units - except wavelength!  

Let's start separate issues on the the standard for how we create new classes and on how we handle input key/value pairs, including units.

So, I will close this one now.
