### ISSUE TITLE
Linear outer segment filter generation and pRate. 

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#174]
In the `osLinear.osCompute()` method, the linear outer segment filters for the L-, M- and S-cones are generated by calling `generateLinearFilters(pRate)` where `pRate` is the mean isomerization rate **computed over all cones** (and all time points), see line 72.

Shouldn't the `generateLinearFilters()` method take as argument the mean isomerization rate  corresponding to each cone type, so that the gain of the linear filter depends on the isomerization rate for that particular cone type?  

Moreover, what about cases in which cones in one region of the mosaic are activated very strongly whereas others are activated very weakly? Should both sets of cones have their  linear filters generated using the same `pRate` value, averaged over all cones ?

**Comment by jamesgolden1** [comment]
@npcottaris I believe Fred mentioned something like this was on his mind in an email he sent to us. 

I looked back at some of the previous iterations of the linear cone computation (coneAdapt.m, riekeLinearCone.m and coneIRFtutorial.m) and didn't see that this had been implemented previously. Fred's 2013 [Nature Neuro paper](http://rieke-server.physiol.washington.edu/Publications/pdfs/natneuro_Oct2013.pdf) is the data for L and M cone responses, which we assume have similar isomerization rates.

**Comment by npcottaris** [comment]
But this is totally wrong for the S-cone linear filter. Also there is the spatial consideration I mentioned above.

**Comment by DavidBrainard** [comment]
Agreed that the means must be computed separately for each cone class.  If we're not doing that, it helps explain why the S cone SNR has been so out of whack all this time.

With respect to inhomogeneous fields, I think this is a case that is best handled by the biophys model.  That is, we know that the linear model is an approximation that assumes a mean operating point, and appropriate only when the stimuli are small modulations around that mean.  That is OK for our detection experiment simulations, where the approximation is by construction of the measurement pretty good.  When we go to more complex stimuli, I think we should move to the biophysical model.

I assume that for the biophys model, each cone is simply driven by its own history and has parameters independent of every other cone, right?

I suppose if the biophys model is simply way too slow we could consider a linearization of it, where we used the linear model for each cone but set the gain based on the average of the isomerization rate seen by that cone in the recent past.

**Comment by npcottaris** [comment]
There is also the temporal issue that bothers me. Right now the pRate mean is computed not only over all cones and all spatial regions but also over the entire stimulation time. In other words the filter at time 0 depends on the future stimulation pattern. This is ok if we are doing modulations around a steady background but if we are presenting natural scenes, or stimuli In which the whole background is modulated this seems like a wrong approach. I think we should.have a way to set the mean pRate directly.

**Comment by fmrieke** [comment]
I completely agree with this (this was what we touched on by Skype a couple weeks ago).  There are enough different situations (both known and unknown) that having more flexibility here would be helpful.  Currently on line 110 of osLinear (at least the version I am working with) the backgrounds are hard coded:

Ib = [7131 6017 1973]; % R* per sec due to background adapting

This is certainly not what we want.  

Having the user specify the mean (if desired) is certainly preferable.  I guess that needs to be a complete image given spatial differences?  And I’m not sure how to deal with time.  I guess if you are doing a simulation in which the mean encountered by a given cone varies a lot with time you could chunk things and respecify the mean - e.g. after each saccade.  

In addition to providing more flexibility, we can push people more to the biophysical model, which takes care of the issue of changing means on its own (because it has adaptation built in).  I have not compared compute times - but at least initially scene generation was taking more time than running the cone models so we did not worry about it much. Likely the biophysical model could be sped up if needed.

Fred

**Comment by jamesgolden1** [comment]
I agree that generally we should move to the biophysical model, and I think the computation time could be improved.

The backgrounds are initially hardcoded on line 110 and are then scaled by the overall mean rate on 113. 

`Ib = Ib * meanRate / max(Ib);`

Would it be worth changing meanRate and Ib to a vector with L, M and S values instead of a scalar over all the cone types?

Another thing to consider is how the photocurrent is computed using the 'append' version with cMosaic.compute, because in that case the entire time course of the pRate is not known for each time step of the current computation. This problem is avoided by computing the current after the isomerizations, which seems to be our standing practice already.

**Comment by wandell** [comment]
How about if @jamesgolden1 and I take a couple of hours to implement a few improvements based on this discussion.  I am a little worried that we might all be working on this, so I am sending this message to check with you.

The plan we are developing is based on the logic below; we welcome your comments.

1.  We separate out conceptually experiments that involve uniform backgrounds and small modulations of the stimulus from experiments that involve, say, natural scenes with high contrast and eye movements.  

This follows a point @DavidBrainard made above. He notes that when using the uniform background, low contrast stimuli, we are OK to use the osLinear model.  But we should use the biophysical model for the more complex case of natural scenes and high contrast scenes.

2.  We re-write the generateLinearFilters() function so that the linear filters under any specific mean illumination condition are consistent with the local linear responses of the biophysical model.  We can enforce consistency between the biophysical model and the local linear model as follows:

    * Calculate the impulse response function of the biophysical model to low contrast impulses,     
    * Build a table of these responses, and 
    * Have generateLinearFilters([L,M,S]) look up the appropriate impulse response for each of the cone types, given their mean levels [L,M,S].

The current linear filters come from a paper @fmrieke  wrote and are derived under specific measurement conditions.  He has already told us that these functions will change with condition.  So, we need to allow the linear filters to change with conditions and this version - building a lookup table by condition - satisfies that need.

There is a thought that we might simply dump the linear model in favor of the biophysical model.  I prefer keeping the linear model, however, because it is so clear, applies to certain conditions, and lets us have a means for people to insert their own linear model (build the relevant lookup table) when they run their own code.

We will branch and work now.  But your comments are eagerly awaited.

**Comment by DavidBrainard** [comment]
I just an hour ago had a discussion with Nicolas about how he might proceed to address this.  I think some key principles are:

a) The mean level should not be hard coded.
b) LMS should always have their own mean levels
c) We have some way to specify the mean levels to the code, either common to all cones (i.e. the uniform field case) or on a cone-by-cone basis.
d) There should be reasonable defaults that work for stimuli that are small perturbations of any uniform fields.  This default might involve setting the gains according to the spatial means for each cone class at time 0.

I also think I would remove anything that is non-causal from the code.  That is, I am very wary of using future responses to set present gain in the actual underlying routines.

I like your idea below of enforcing consistency between the biophysical model and the linear model for uniform fields.

I will let Nicolas chime in on what he is doing right now, and whether that is likely to collide with what you guys are about to do.

Best,

David

**Comment by npcottaris** [comment]
I am currently not working on `osCompute`, but I am working on `coneMosaic.computeForOISequence`. 

So all clear by me.

**Comment by fmrieke** [comment]
These principles and Brian’s message below on approach seem good to me.  I like imposing identify of the biophysical and linear model for low contrast stimuli.  And I agree that the linear model is very useful in cases where the mean is well determined.

Fred

**Comment by jamesgolden1** [comment]
I added a branch 'osLinearize' that implements the objectives @wandell described above. Changes were made to osLinear.m and osCompute.m. A function called generateBioPhysFilters was added to osLinear.m. 

generateBioPhysFilters builds the impulse responses internally with osBioPhys, and passes these as filters to the osLinear object. The magnitudes are scaled appropriately (so far as I can tell) for the isomerization rates of each type of cone in @osLinear/osCompute.m, lines 75-100. I have been comparing the magnitudes of these new linear filters from the biophysical response with the original linear filters from the coneIRFtutorial.m of @fmrieke and it makes sense so far. I will build a validation or tutorial script that shows this.

**Comment by wandell** [comment]
I believe that osLinear is no fully updated, the coneMosaicWindow is updated, and the calculations of noise agree with @fmrieke papers.  The movies are running for the rectangular case (I haven't started to think about the hex case, but I have seen various things from @npcottaris being worked out).

I am closing this issue because the work is drafted.  When @jamesgolden1 implements some of the validation coding update, we can ask for a review and then merge.
