### ISSUE TITLE
coneMosaic.compute

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#192]
I am in the process of fixing up the noiseFlag for random/frozen/none.  

In that process, I noticed that we manage the emPath in coneMosaic.compute a little oddly.  When absorptions is empty we simply place 'emPath' to the current emPositions.  But if there are absorptions, we add emPath to the existing positions. 

I would prefer getting rid of this 'emPath' parameter altogether and just having people set the coneMosaic.emPositions before we get here.  But if we can't do that, then I would prefer doing the same thing with emPath (i.e., setting emPositions to emPath) no matter the current state.

Here is the current code that I would like to replace.  I think the behavior is too subtle for a blunt guy like me.

   ```
%% set or add to eye movement path
   if isempty(p.Results.emPath)
     emPath = obj.emPositions;
    else
     emPath = p.Results.emPath;
     if isempty(obj.absorptions), obj.emPositions = emPath;
     else
        obj.emPositions = [obj.emPositions; emPath];
     end
    end
```

**Comment by npcottaris** [comment]
Agreed. Never liked this as well. I thought it was a remnant of the 'append' flag which I also was not particularly fond of.

It is ok with me to get rid of the emPath in the compute method which contains the emPositions for a single trial. I kind of like passing emPath as an argument to compute because this allows a more direct association of the absorptions signal with the passed emPath, but if you prefer not to that is fine too.

Note however that the computeForOISequence method expects an emPaths parameter which contains the emPositions for nTrials. We probably want to keep that one unless we allow the emPositions property to contain paths for nTrials.

**Comment by wandell** [comment]
You're up too late.
OK, done.  And we will keep the emPath flag because it is necessary, as you point out.
I have implemented this already on the bipolar branch, so let's close this.
