### ISSUE TITLE
Reorganization of bipolar, rgcMosaic and ir objects into a parallel structure.

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#221]
The bipolar object is equivalent to the rgcMosaic, not the inner retina object. We really want a bipolarLayer object and a bipolarMosaic object, parallel to the ir object and the rgcMosaic object.

The bipolarLayer object could bring up a window to visualize one of the set of mosaics.  We should be able to select which one from a listbox on the window.

Similarly, the rgcMosaic.window should be replaced by an ir.window.

We can use a listbox we should select which mosaic we visualize in both the bipolar and rgcMosaic cases.

If we want to visualize two mosaics at the same time, say to compare, we can bring up two windows and select different mosaics.

**Comment by wandell** [comment]
I am also wondering about nomenclature.

I wonder if we should rename ir the rgcLayer. 

Perhaps we should create the "innerNuclear" layer, a real term, or bipolarLayer, which is a term we would be making up. The real innerNuclear contains bipolars and other cell types.

If we ever made an outer nuclear layer it would contain the coneMosaic and the rodMosaic. That seems unattractive to me because there really is only an interleaved photoreceptorMosaic rather than two mosaics.  Still, not sure.

My vote - but I am curious about you all - is coneMosaic, bipolarLayer, and rgcLayer.

**Comment by JWinawer** [comment]
I like bipolarLayer and rgcLayer. I don't know what plans have been discussed for rods. If rods are to be included at some point, then one could either have a rodMosaic and coneMosaic in an outer nuclear layer, or a single photoreceptorMosaic with 4 receptor types. I suppose there are advantages to both. In any case, a bipolarLayer with multiple mosaics, parallel to the rgcLayer, is a good idea.

**Comment by chichilnisky** [comment]
I can only comment on naming.

I certainly like rgcLayer

as to bipolarLayer, that probably seems like the right term. I don’t think we’re trying to match anatomical regions as much as functional groups. If we were to add amacrine cells, they would probably live in an amacrineLayer object, even though they actually occupy the same physical area as bipolars. Not to mention the fact that there are amacrines in the RGC layer.

Thus, bipolarLayer and rgcLayer are functional layers, not physical spaces.

Right?

ej

On Jun 8, 2017, at 10:15 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


I am also wondering about nomenclature.

I wonder if we should rename ir the rgcLayer.

Perhaps we should create the "innerNuclear" layer, a real term, or bipolarLayer, which is a term we would be making up. The real innerNuclear contains bipolars and other cell types.

If we ever made an outer nuclear layer it would contain the coneMosaic and the rodMosaic. That seems unattractive to me because there really is only an interleaved photoreceptorMosaic rather than two mosaics. Still, not sure.

My vote - but I am curious about you all - is coneMosaic, bipolarLayer, and rgcLayer.

**Comment by render-toolbox** [comment]
Can we define a parent "layer" class and have rgcLayer, bipolarLayer etc. be subclasses that inherit much of the same code?

**Comment by fmrieke** [comment]
I think this would be ideal.  Each layer is going to integrate over inputs and apply some sort of output transformation, so there is a ton of commonality.  

Fred

**Comment by wandell** [comment]
This implementation is first-order done and being used by a couple of groups.  So, I will close this issue.
