### ISSUE TITLE
Differences in irradiance computation

### ISSUE THREAD

**Issue by beyondmetis** [isetbio/isetbio#223]
I think the isetbio formula for computing irradiance is well-justified in isetbio/isettools/opticalimage/oiCalculateIrradiance.m

Irradiance = pi /(1 + 4*fN^2*(1+abs(m))^2)*Radiance

However, I was reading "Chromatic detection from cone photoreceptors to V1 neurons
to behavior in rhesus monkeys" where the irradiance is computed in equation 6 as

Irradiance = Radiance * pupil_area / (eye_diameter^2) * 10^(-12)

I know that fN should be focal_length / pupil_diameter, so this leads me to believe that the simpler equation (equation 6) is an approximation that at minimum doesn't consider magnification. I'm not sure if this an appropriate forum to ask, but does anyone know how this approximation is derived?

PDF of paper:
http://rieke-server.physiol.washington.edu/Publications/pdfs/jov_Nov2015.pdf

Also, is there any plan to incorporate pupil adaptation into isetbio, since that directly modifies irradiance computations?

**Comment by DavidBrainard** [comment]
Hi, and thanks for your interest.

Have you looked at script validation/scripts/radiometry/v_IrradianceIsomerizations.m?  This checks the calculations of irradiance and isomerizations done by isetbio against the way it is done in the Psychophysics Toolbox (psychtoolbox.org).  There is an explicit step where an adjustment to the PTB calculation (which just uses simple trig to get retinal area) with the fancier formula you describe above so you can look at the effect of that if you take it out of the comparison.  There are also some comments noting that the agreement is good to about a percent.  We decided that was plenty good enough given uncertainty in many of the underlying parameters.

The Rieke formula agrees (up to choice of units) with the formula implemented in PTB's PsychRadiometric/RadianceAndPupilAreaEyeLengthToRetIrradiance.  The code there contains a derivation in the form of a longer commented out computation, and the directory PsychRadiometric contains routines for doing many radiometric conversion related to your general inquiry.  You might have a look over that code.  I tried to document things fairly carefully as I wrote that code, but I'm sure it could be better.  If you have explicit suggestions of where more information would have helped, send along draft text for insertion and I'll review and incorprate.  There is a script, RadiometricConversionsTest, that exercises the conversions routines and demonstrates a basic level of self-consistency.

With respect to your question about pupil adaptation.  I think you mean, do we plan to have the code estimate the pupil size from the stimulus and dynamically update it in the calculations?  That would be cool, but a little tricky.  For example, to do it right you'd want to update the optical point spread function with the pupil size, and also estimate the pupil size from the cone responses rather than from the luminance of the stimulus. The published formula I know of start with the luminance so we'd have to do some work to back them into the visual system.  I think we could do that, but it would be a bit of a project to do it well.  I think in the near term we are not going to do much about this.

There is an implementation of various formulae for estimating pupil size from stimulus luminance in the Psychtoolbox.  See PsychColorimetricData/PupilDiameterFromLum, and that routine is included in the subset of PTB routines that we bundle with isetbio.  (I think the radiance routines mentioned above are as well.)  So you could use that in a script to estimate the pupil size from the scene and then set it for the rest of  your calculations.  On our list is to add Watson's recent formula to the list of options in PupilDiameterFromLum.

We're open to folding in contributions, if you make progress on things that aren't yet implemented.

**Comment by wandell** [comment]
Yes, thanks for your interest.


Quick follow-up - was David's guess about your meaning of 'pupil adaptation' correct?


Brian

________________________________

**Comment by beyondmetis** [comment]
@DavidBrainard Perfect! The comments made in PsychRadiometric/RadianceAndPupilAreaEyeLengthToRetIrradiance fully explains to me where this simplified formula comes from.

@DavidBrainard @wandell This is 100% what I meant by pupil adaptation. The pupil size function that depends only on stimulus luminance is good enough for me. At some point, it would be cool to have a function that captures how the pupil adapts to changes in luminance over time. I'm not sure any data exists for this, and I don't know what collection of signals drive pupil size. My knowledge is quite limited here.

Thank you for this amazing tool! As I make progress in my research, I will contribute what I can for your review, as that would benefit everyone.
