### ISSUE TITLE
s_ versus t_

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#230]
Is this a meaningful distinction for us.  If so, what is it?  Or are s_ things really tutorials?

**Comment by wandell** [comment]
Mostly scripts do experimental calculations rather than teach about them.  And mostly they should be in working repositories, say when we write a paper.  

During the recent work, however, I needed scripts to test and try some stuff.  Like we kept changing the API on major new classes, and I needed a place to experiment with the look of the code.  I called them scripts.  I hope they will turn into either validations or tutorials within the repository. I can see how we might prefer to have only tutorials in the main release.

**Comment by DavidBrainard** [comment]
OK, that works for me: scripts are things that are likely to someday grow up to be something else, but where for now we're not sure exactly what.

**Comment by wandell** [comment]
True.  You might wonder why they get checked in at all.  Mostly this is for my convenience as I shift  between working computers.

But, maybe these scripts should only get checked into the working branch, and they should be deleted by the time we merge into the master.  In a more perfect world, I will do that.  Trying.
