### ISSUE TITLE
osAddNoise temporal dynamics

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#244]
In `osCompute()`, noise is added to the noise-free photocurrent by calling `osAddNoise` with a passed `sampleTime` option equal to the sample time of the @osLinear, which is 0.1msec. This is the resolution with which the linear filter is computed. 

However, the noise-free photocurrent is computed by convolving he absorptions signal with a downsampled (to the absorptions timebase) version of the linear filter, which is usually 5 msec.

This discrepancy between `sampleTime` for `osAddNoise` and the timebase of the noise-free photocurrent computation seems wrong to me. I think the `sampleTime` passed to osAddNoise should match to the timebase of the linear filter used to compute to noise-free photocurrent.

Opinions anyone?

**Comment by wandell** [comment]
It seems wrong to me, too.  The noise distribution should be calculated based on the sample time of the absorptions.  There is a normalization term on line 90 of osAddNoise that divides by the sample time, and I think that sample time should match the time base of the absorptions, not the general time base of the photocurrent (0.1 ms).

But on line 169 et seq. of osCompute, we are sending in the sample time of the outersegment object, when we **should** be sending in the sample time of the conemosaic object.  So, that is an error.

This was an easy mistake to make because the code refers to obj.timeStep; the author might easily have thought obj referred to the cone mosaic, not the outer segment.  Or, perhaps, there was some point in time at which the outer segment time step was forced to be the same as the cone mosaic time step. 

In either case, I think we need to get the time base of the cone absorptions and send that in when we compute the noise.  So, I think you discovered a real conceptual bug.

**Comment by render-toolbox** [comment]
I didn't look at the code here, but I agree that the noise should be added with respect to the time base of the thing it is being added to.

So if the os photocurrent is computed on a timebase of 5 msec, noise should be added for that timebase, and not the faster timebase that was used to run the differential
equations to compute the linera filter before it was downsampled.

DB

**Comment by fmrieke** [comment]
I think the most important thing here is to make sure the noise has the correct power spectral density.  The target for the noise calculation is a certain power spectral density as a function of frequency - and if the calculation is working the way it should, that should not depend on the temporal sampling.  It makes sense though to compute the noise on the ‘output’ time base.  

Fred

**Comment by npcottaris** [comment]
I was writing  code to check the spectrum of the computed noise vs that of the true photocurrent noise just as Fred was suggesting the same !

It turns out that the intuition we all had was correct. When using the`@osLinear` class, which computes photocurrents using the subsampled os temporal impulse responses, the `sampleTime` passed to `osAddNoise` must be the `cone integration time`, NOT the `os.timeStep`. 

In the attached figures below, I am comparing the spectrum of the directly computed photocurrent noise to the spectrum of the noise derived from the photocurrent responses to some stimulus. When `osCompute` passes the `cone integration time` to `osAddNoise` the spectra of the two noise signals match exactly (see normalized spectra in the figure below).

![integrationtime](https://user-images.githubusercontent.com/3444212/29383916-34c4cba2-82a0-11e7-80d8-a1f94d1a5e40.png)

Also note that the ratio of the blue raw spectrum to the red raw spectrum in the figure above is 50, exactly what is expected given that the cone integration time was 5 sec and the os.timeStep was 0.1 msec.

When `osCompute` is passing the `os.timeStep` to `osAddNoise` the spectra of the noise signals differ radically (figure below).

![ostimestep](https://user-images.githubusercontent.com/3444212/29385900-7efed71a-82a7-11e7-99c0-e79d2e3e2748.png)


Note that, compared to the true noise, the incorrectly computed photocurrent noise had more power in the range 0-5 Hz, and less power for frequencies > 5 Hz. 

Bugfix is now pushed to master. This will break some validations. I will fix those tomorrow.

Nicolas

**Comment by DavidBrainard** [comment]
Do we have a validation that compares these spectra to the underlying measurements, to verify that we have it right?

**Comment by wandell** [comment]
At one point,  @James Robert Golden<mailto:jgolden1@stanford.edu> and @Cottaris, Nicolas<mailto:cottaris@psych.upenn.edu> and I were making noise spectrum plots comparing our implementation with the Rieke curves.  They were very closely matched.


I am looking, and I only see t_osNoise.m.  I think that might be what I am thinking about.  It matches at the top (flat line), with the Rieke predictions.


Maybe there is something better (like a match to the whole theoretical curve).  But at least I remember that the pA^2/Hz top level matches between the numbers in the paper and our code.


________________________________

**Comment by npcottaris** [comment]
I found a PDF that Fred had sent us a long time ago which described his photocurrent adaptation model and which contained a measurement of the noise spectrum. I digitized it and superimposed it to the curve generated currently by isetbio. The measured spectrum is shown in blue, Fred's model fit is shown in red, and the spectrum of the ISETbio-generated noise is shown in black (after a vertical shift, so that it matches in max value to Fred's data). Like Brian recollects, we have pretty good agreement up to 40-50 Hz, but at higher frequencies the two spectra deviate significantly.

<img width="954" alt="agreement" src="https://user-images.githubusercontent.com/3444212/29431812-48d4e2ea-8367-11e7-9fe0-dbd45e11d1b0.png">

It would be great if @fmrieke provided some physiological data (raw noise traces, not the spectra) so we can validate physiological data to ISETbio generated data using identical spectrum computations.

**Comment by wandell** [comment]
That's a good find!  I think the shift to match at 0Hz is legitimate because of the t_osNoise.m agreement, which is based on their data.

I think it would be fine to get this closer, but notice that the noise level is almost an order of magnitude down from peak where it starts to deviate.  So, we should probably carry on using our calculation for now.  I guess this is me saying that we differ, but maybe not 'significantly'.  The noise we produce has mostly the right power spectrum, though about 50 Hz we might be a little bit under powered.

It would be swell if Fred had some more examples.  It would be nice to know how much the data (subject-to-subject) and conditions vary in comparison to the difference between the black curve and the blue points.

**Comment by fmrieke** [comment]
I’ll have to look at the routine and see where the difference comes from (at some point we were calculating the noise using the fit spectrum directly - so the power spectra were essentially identical).  Power spectra are the best thing to look at because we need to use them to isolate cellular noise from recording noise (i.e. if I give you a trace of recorded noise in the time domain, you don’t know what fraction of it can be blamed on the cell and what is due to instrumental noise in the recording - by going to the frequency domain and measuring instrumental noise we can subtract it out).

The data in that plot is an average across a collection of cones.  I’ll look for more individual examples, but I think the difference between black and red traces is larger than the cell-to-cell variability.  

Fred

**Comment by npcottaris** [comment]
Noise power spectra for a typical cell would be great to have for validating ISETbio code.

Also, while we are in this mode, could you also give us typical foveal and peripheral outer segment responses for which the foveal and peripheral impulse response parameters provide a good fit? It would be good to have validation scripts that check these as well.

**Comment by DavidBrainard** [comment]
I don't understand why there should be a free vertical shift to fit the measured noise.  Isn't the noise in absolute units that we want matched to our photocurrent?

**Comment by npcottaris** [comment]
It depends on how you scale the spectrum. That is why I was asking for the  raw data, so we can use the same spectrum routines on both signals. If we cannot get that, we should know how the spectrum is scaled in the Rieke lab, so we can use the same scaling factor.

**Comment by fmrieke** [comment]
There should not be any vertical scaling if you measure noise spectral density - because in that case the arbitrary factor (the length of time you made the measurement) gets normalized out.  I have attached the routine we use for this.  Basically what it does is computes the noise spectrum as

Noise = 2 * fft(signal) * conj(fft(signal) / time

where the 2 comes from making the power spectrum single sided (i.e. there are both negative and positive frequencies in the spectrum, and if we are only keeping track of the positive part of the spectrum we need the 2 to get the total signal variance correct).  time is the total length of time of the recording.  If this is computed correctly, integrating the noise spectrum should give you the variance in the time domain with no scaling (where the integral includes the correct frequency sampling integration factor).  

I’m happy to find some raw data, but it will have this problem of including instrumental noise so is not the ‘correct’ target for the calculation.

Fred

**Comment by npcottaris** [comment]
And the FFT(signal) is computed without zero padding, even if the # of time samples is not a power of 2, or you make sure you have a power of 2 data length?

**Comment by fmrieke** [comment]
Correct - no zero padding (or windowing of other types).  We usually chose a factor of two data length.

Fred

**Comment by npcottaris** [comment]
This issue has been addressed. Noise is computed in the time base of the response, not in the time base on which the impulse function is computed.
