### ISSUE TITLE
Wavefront Part II Issues: Broken Examples: compute folder

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#264]
This issue will include files from the [isetbio/isettools/wavefront/compute/](https://github.com/isetbio/isetbio/tree/master/isettools/wavefront/compute) directory. There will be other issues created for the sub-directories as needed (for general notes, etc) and specific issues for fix requests, problems, etc.

File: wvfComputeOptimizedConePSF
 - [Note: JNM - The example is broken, but at least 'semi-present' now]
 - How to handle inline function?

File: wvfComputeOptimizedPSF
 - [Note: JNM - The example is broken, but at least 'semi-present' now]

**Comment by DavidBrainard** [comment]
These two routines were not finished, which is why it is hard to get the examples to work.  Nor are they used anywhere that is not itself marked as under development or commented out.

I changed the enclosing directory name to underDevelopment_wavefront to indicate the current status.  We may someday want to explore the effects of the focus optimization that these routines are meant to implement, and they are probably close to working because they were before the wavefront toolbox was folded into isetbio.  But for now I am closing this issue.  I will open a separate issue that indicates that the functionality these routines were aiming for might be nice to have some day.
