### ISSUE TITLE
Wavefront Part II Issues: General Issue 02, iset folder notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#265]
This issue will include files from the [isetbio/isettools/wavefront/iset/](https://github.com/isetbio/isetbio/tree/master/isettools/wavefront/iset) directory. There will be other issues created for the sub-directories as needed (for general notes, etc) and specific issues for fix requests, problems, etc.
File: wvf2oi
 - In the oi section... "Note the awful repetition of setting the wave. Sigh. This should get better. " What about this needs to improve? What is the expected timeline (if ever) for this to happen?

File: wvf2PSF
 - [Note: JNM - What dictates the hard-coded values such as pixels, microns per sample, etc... below?]

**Comment by DavidBrainard** [comment]
On the first point, I think that got fixed because in the code there was only one set of wavelength. The other had been commented out.  It looks like the stored otf now has its own wavelength samples and that only these need to be set.  But, I did add a note at the top of wvf2oi that we might verify that.  Indeed, I added a bunch of notes based on my reading of the function.  Here they are:
%  * [NOTE: DHB - There is an interpolation in the loop that computes the
%     otf wavelength by wavelength.  This appears to be there to handle the
%     possibility that the frequency support in the wvf structure could be
%     different for different wavelengths. Does that ever happen?  If we
%     check and it doesn't, I think we could save a little time by getting
%     rid of the interpolation.]
%  * [NOTE: DHB - NCP and I spent a lot of time last summer suffering
%     through the psf <-> otf calculations as part of the IBIOColorDetect
%     project, and the fftshift conventions.]
%  * [NOTE: DHB - There is a note that PSF might start real but that the
%     PSF implied by the OTF computed here might not be.  We should check
%     into that.  We don't want imaginary PSFs showing up in calculations.
%     Perhaps this is handled by the oi methods, in that perhaps they
%     enforce that the psf obtained from the otf is in fact real.]
%  * [NOTE: DHB - It might be worth checking that it is OK just to set the
%     wavelength on the OTF, even if the oi itself has different wavelength
%     sampling.]

**Comment by DavidBrainard** [comment]
The hard coding of the numbers in wvf2PSF also makes me nervous.  And, that routine is not called anywhere that I can find.

I think we should harmonize wvf2PSF and wvf2oi with code that NCP and I wrote in IBIOColorDetect that does similar things, and try to make it all a bit clearer and more bulletproof.

**Comment by DavidBrainard** [comment]
I fixed up wvf2PSF quite a bit, using input parser to allow the hard coded parameters to be set and tuning up the comments/examples.  This probably isn't particularly useful since that function was never called, but I understand it now.  I will move towards writing a validation script that compares across the many separate places we do these sorts of conversions.

**Comment by DavidBrainard** [comment]
Most of this is handled, but leaving open because there are still a few notes left in wvf2oi.

**Comment by DavidBrainard** [comment]
Handled notes in wvf2oi.  Closing.
