### ISSUE TITLE
isettools/utility Part I Issues: Function usefulness

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#277]
This issue is to bring to attention functions that may or may not be better served by using MATLAB built-ins. I would like to use this issue to start the conversation, at least, about the below functions.

isetbio/isettools/utility:
 - rad2deg - _Now renamed to ieRad2deg, see BAW comment below..  This probably exists because there wasn't always rad2deg in Matlab, and now we want it for backwards compatibility given our calling conventions about units.  DHB._
   = Fixed examples & description
   = I don't understand why we have this function when there exists radtodeg and toRadians, which both accomplish similar or identical tasks
 - isodd - _Exists for clarity, see BAW comment below. DHB._
   = What is the point of this method?
   = Notes:
       * [Note: XXX - Perhaps there should be an 'iseven' routine]
       * [Note: JNM - Changed the output variable from bool to cal in order to avoid clobbering the function bool(b)]
       * [Note: JNM - This function only returns reasonable answers when provided with integer inputs.]
 - deg2rad - _See above and below.  DHB._
   = Notes:
       * [Note: XXX - Perhaps this routine should also adopt the varargin structure in that function.]
       * [Note: JNM - Added in units section (that changed from rad2deg) - please check over my work!]
   = Please see my notes in the history section to see the changes I've made. However, I am of the opinion that like rad2deg, this function may be excessive compared to a number of the built-in functions that MatLab provides

**Comment by wandell** [comment]
Deprecated rad2deg and deg2rad in favor of the Matlab functions.
Used ieRad2deg and ieDeg2rad in place of the current calls.  In the end, we should probably change our functions to rely on the mathworks built-in functions.  

isodd() is needed to check if a number is even or odd for various matrix operation cases.  Using this function rather than the mod(x,2) is a little clearer.  The current form is not as complete as we would like.  I added in a much more complete function that tests for single/double/int and so forth.  It is in only as a long comment, not implemented.  We should think about whether we want to make this change.

**Comment by DavidBrainard** [comment]
Although there is little stuff pending here, I think the issue can be closed.  Note that toRadians might be in a specialized toolbox not part of main Matlab.
