### ISSUE TITLE
WVF and the pupil function

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#280]
DHB points out that the pupil function we measure for, say, 7mm should agree with the pupil function we measure for 3mm in the central 3mm of the lens.  So, if we store the pupil function at 7mm we ought to be able to recreate the pupil function for arbitrary size pupils just by masking out the peripheral part of the pupil.

We need to check whether the Thibos data we have is consistent with this idea.  That is, do the pupil functions he provides at 3, 4.5 and so forth agree in the portions of the pupil where they overlap.

**Comment by DavidBrainard** [comment]
I just discovered that opticsCreate('wvfhuman') [which is called by oiCreate('wvfhuman')] always loads the 3mm Thibos data, even if you pass a larger pupil size.  So, the wvf data will be incorrect unless you stick with the default 3 mm or smaller.  The best way to fix this depends a bit on our investigations of the point above -- ideally we can load the Thibos data for the largest pupil size, throw an error if you ask for a size bigger than that, and then happily proceed.

I am not changing this yet, because I am in the middle of too many other fussy things and am feeling like I need to make small changes and verify that I can keep the validations running, changing validation data only when I have made a point change whose effect I understand.

But we need to fix it before we do any wvf calculations using pupil sizes other than 3 mm.

**Comment by DavidBrainard** [comment]
Have now addressed this issue.

First, t_wvfPupilSize shows that the various Thibos data produce almost the same psf if you set the measured size to match the measurement size and keep the calc size fixed at 3 mm. Presumably the differences are because the different data sets represent different real measurements.

Second, opticsCreate('wvfHuman') now loads 7.5 mm and sets the measured size to match, with the calc size at 3mm.  

Closing.
