### ISSUE TITLE
isettools/utility changes Part II Issues: Examples

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#282]
This issue is to cover examples in the Part II check-in that are not fully functional. The top section contains examples that are broken and I was unable to determine how to fix, and the bottom section contains examples that I was able to get functioning, but am not sure if they properly use their function(s). Please let me know if anything is unclear! 
Broken Examples:
- hcimage
- imageDataXYZ
- imageMultiview
- imageMontage
- imageShowImage
- oiPlot
- svmClassifyAcc

Examples I am not sure are working as intended:
- hcimageCrop
- hcimageRotateClip
- imageLinearTransform
- imageRotate
- imageMakeMontage
- imagescOPP
- imageSPD

**Comment by wandell** [comment]
imageShowImage can be deleted.
Fixed hcimage and related routines.
Fixed imageLinearTransform and added management of XW format
Pointed out s_oiPlot tests.
Removed imageDataXYZ
Checked other examples and amended (imageRotate, imageMakeMontage, imageSPD
Removed imagescOPP because it i not really biological enough and wasn't fully implemented.
imageSPD seemed fine.

Did not deal with swvmClassifyAcc, which will need to be addressed more extensively when we start to manage that part of the computational environment more thoroughly.

So, closing.
