### ISSUE TITLE
What type of classifier to use for computational observers

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#29]
If James and I are reading svmClassify.m correctly, it is using an svm with a radial basis kernal by default.  I'm not sure this is what we want as the default.  Maybe using linear classifiers as a point of departure would be wise?

**Comment by hjiang36** [comment]
I guess you mean svmClassifyAcc.m (svmclassify.m is in stats toolbox).

For svmClassifyAcc, I thought if we would like to have linear kernel, we use liblinear method instead of libsvm (it's much faster anyway). Not sure if we would like to have all of them use linear kernel by default.

Also, shall we move classifiers to another repository (say, computationaleyebrain)? It's not a part of isetbio and we might have random forest, cnn or some deep learning stuff in the future.

**Comment by DavidBrainard** [comment]
Closing.
