### ISSUE TITLE
isettools/sceneEye changes Part I Issue: render TODO's

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#290]
Assign some person(s) to handle the To-Do list for this function
* TODO: Is clearing most of the default optics okay? Determine if there is a better way to accomplish this.
* TODO: Is it possible to remove the need to specify the type and value for the chromaticAberrationEnabled?
* TODO: Determine if it is alright to remove unset and unused output variable outputFile

**Comment by tlian7** [comment]
Fixed. Some comments:

> TODO: Is clearing most of the default optics okay? Determine if there is a better way to accomplish this.

There have been no issues so far, so I think we can leave it as is. In the future I imagine we might want to fill in more of the optics parameters. It might even be necessary as we utilize more of ISETBIO's analysis functions. 

> TODO: Is it possible to remove the need to specify the type and value for the chromaticAberrationEnabled?

I made some changes to pbrt-v2-spectral to remove the redundant chromaticAberrationEnabled flag, so we no longer need this anymore. I removed it from the ISETBIO code as well.

> TODO: Determine if it is alright to remove unset and unused output variable outputFile

No issues with this, the outputFile variable was never used anyway since it's saved within the recipe class already.
