### ISSUE TITLE
vcSelectImage

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#298]
Carrying forward from #274.

The image types don't seem to be respected by the calls in the examples, as far as I can tell. Maybe I don't understand what the routine is supposed to do.  See notes from Jenn.

**Comment by wandell** [comment]
There were many things wrong with the vcSelectImage function.  A lot of these could be traced to problems with the vcSelectDataFile function, which still had old residues from mrVista, it didn't handle any of the new ISETBIO functionality.  Oh well.

I re-wrote vcSelectDataFile, removing ridiculous old variables ('session') and changing the logic a bit.   Then I re-write vcSelectImage, which calls vcSelectDataFile.  Seems kind of OK to me now.  Hard to test thoroughly.

Note:  I didn't delete it because vcSelectDataFile, in particular, has a useful feature.  It uses the persistent variable mechanism in Matlab to remember the last directory you selected. So, when you click your way somewhere to load data, it remembers where.  The next time it is called, if you use the '' or 'stayput' options, it opens up in that same directory.  That functionality is worth having.  

I rewrote the examples and tested some.  Hopefully this now makes sense and will be useful.
