### ISSUE TITLE
coneAbsorptions, noise flag

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#30]
We noticed that coneAbsorptions ignored the setting of the sensor's noise flag.  We modified it so that it does not add noise when the noise flag is 0.  

If this is fine, you can close this issue.  If it's not good, then we need to find another way to get noise free cone responses.  David and Xiaomao

**Comment by fmrieke** [comment]
That seems a good call to me …

Fred

**Comment by wandell** [comment]
This may be a general problem because at some point in time sensorCompute and coneAbsorptions diverged.  I have been paying attention to sensorCompute, but not coneAbsorptions (mainly because most of my work is in ISET, not ISETBIO).  I will try to spend some time with HJ checking and confirming with you.

Also, in ISET I was asked to introduce a noiseFlag -1 condition - which I did.  I will try to explain that and make sure coneAbsorptions follows that protocol, as well.

It is a real pain having two parallel pieces of code, but nothing to be done.

**Comment by xnieamo** [comment]
Closing this as this has been addressed I think.
