### ISSUE TITLE
Contributing code analyzing Jaeken & Artal dataset with higher order optical aberrations

### ISSUE THREAD

**Issue by elinekupers** [isetbio/isetbio#342]
I wrote several functions that digest the data kindly provided by Bart Jaeken and Pablo Artal on higher order aberrations in emmetropes and myopes in the periphery (published in 2012, see https://www.ncbi.nlm.nih.gov/pubmed/22511633). They are stand alone functions and one tutorial. I tried to stick my code writing to the ISETBIO conventions so they can easily be added.

I would like to share my code, so others can test the code and eventually contribute to ISETBIO. Any thoughts on what would be the best way to go? Currently I don't have permission to add a new branch; I can only send pull requests. I could also use our project repository isetbio/JWLOrientGabor?

Thanks!

**Comment by DavidBrainard** [comment]
This sounds great!  I have just invited you to the isetbio core team, so once you accept you should be able to create a branch and add your code.

Why don't you stick it in a branch and let us know, we can review and then merge it in.  I think these things would be great to have in isetbio itself as they will be valuable to many projects.

**Comment by elinekupers** [comment]
Great! Thank you! I pushed the branch JaekenArtalHO (HO for Higher Order aberrations).

Data can be found in: `../data/datafiles/human/wvf/` and corresponding code loading the data in `../data/dataroutines/wvf/`

The tutorial is in `t_wavefront/underDevelopment/t_wvfJaekenArtal2012.m` plotting the averaged PSF and OTF across emmetropes or myopes for the requested eccentricity.

**Comment by wandell** [comment]
This is really great, thanks!  I am making sure @tlian7  knows about the new code.  She will be able to compare this work with the Navarro eye model.  Will you be at VSS?  Trisha will be there.

**Comment by elinekupers** [comment]
Yes I will!  I'm looking forward to meet her and maybe we can find a time to discuss the projects.

**Comment by DavidBrainard** [comment]
Yes, let's have an ISETBIO summit at VSS.  Will try to merge your branch in today.

**Comment by DavidBrainard** [comment]
Tried this out.  We seem to be missing a function zernikeDefocus2diopter.  This is called by wvfSortSubjectDataJaekenArtal2012.

Note that there is a function in isetbio called wfvDefocusMicronsToDiopters (isettools/wavefront/utility) which might (or might not) do the same thing.

I merged the current master into the JaekenArtalHO branch and made a few cosmetic changes to the header comments. Pushed up to gitHub.

Will try again once we resolve the missing function issue.  I'm guessing it is somewhere on your path (maybe in the project you use this with).

**Comment by elinekupers** [comment]
Thanks for checking! Yes, that's right. I wrote that function for my project before I found "wfvDefocusMicronsToDiopters", but they have the same inputs and do the same calculation. So feel free to replace the zernikeDefocus2diopter function with the isetbio wfvDefocusMicronsToDiopters function.

**Comment by DavidBrainard** [comment]
Merged in your branch and deleted it.  It is great to have this code inside isetbio.  Everything worked once I switched to wfvDefocusMicronsToDiopters.

A few notes:

a) I renamed the load function to be wvfLoadWavefrontOpticsData.  Eventually we should use this to load data from other sources, such as Thibos.  Modified tutorial to match (and explicitly specify the source.)  I think the more generic name will serve us well in the future.  I left the sorting function as named, since that is highly specific to the Jaeken/Artal dataset.

b) Take a look at the edited header comments in the various functions, which I edited to more closely match our conventions.  All minor. The things I remember:
  i) Remove blank lines between bits of header comments, so the whole thing will show up when you   
  type "help xxx"
  ii) Document key/value pairs under "Optional key/value pairs" rather than under "Inputs"
  iii) Move examples to block comment style, after history and under a line that starts "% Examples:"
  This lets the ExampleTestToolbox find them.  See ieRunExamplesAll.
  iv) Specify defaults and allowable options in header comment, for key/value pairs.

c) I added a 'verbose' key/value pair to the routines, and set its default to false.  This suppresses all printout and plotting.  Set it to true in the call from the tutorial.  I like to keep control of printout from
functions, so that the calling program has control of whether things show up printed in the command window etc.

d) Moved tutorial out of the under development directory.

Looking forward to playing with these data/functions more soon.

Thanks again for writing this in such a nice and orderly fashion, and for providing the tutorial!
