### ISSUE TITLE
Function poirsonSpatioChromatic broken

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#372]
It is broken because it calls a function called sumGauss, which we do not have in isetbio.  If someone (@wandell ) knows where this function is and adds it to isetbio, this might work.

I put ETTBSkip on the examples in this file, as well as in the example in humanSpaceTime that invokes this function.

I also put a note in the description that the function is currently not working. 

If someone fixes this, please remember to delete the comment about not working, then try the examples and remove the ETTBSkip lines from the ones that work.

**Comment by wandell** [comment]
I added sumGauss.m from ISETCAM to isettools/metrics.

I ran the examples in the file, but they were not formatted according our standard and had no ETTBSkip in them.  Perhaps this is due to a branch issue or commit?

@DavidBrainard - Still, the stuff seem to run now.  If you are OK with the version you have, please close.

**Comment by DavidBrainard** [comment]
Yes, I managed to commit the changes locally but not push.  That's done now.

In sumGauss, I changed ieNotDefined to notDefined, as we don't have the former in isetbio.
Then found functions it needs, gauss() and gauss2() and added these.  Applied ieNotDefined
fix to gauss2().

Now it all works.  Fixed up comments and removed ETTBSkips. Closing.
