### ISSUE TITLE
Tutorials Pass I Part III: Cones

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#376]
Tutorials Pass I Part III Cones
- t_conesPhotoPigment: There is a cell describing wavelength despite that it is instantiated in a prior cell. I'm trying to decide how much (if at all) that I like this. It is is useful for calling out pertinent information, but perhaps it should be before the creation of the photoPigment object?
- [x] t_conesMosaicHexReg: Please take a look at some of the modifications I've made for spacing, and how I moved the commentary for the mosaic parameters to being prior to the assignments, rather than inline.
- [x] t_conesMosaicHex: mosaic fov is a vector, but the fovExamined parameter is a numeric? Is this intentional?

- [x] t_conesMosaicAbsorptionEccBased: 
       - [ ] Need to fill in the key/values section of the support function plotMosaicActivation! (L432+) -> Not sure if there are more possible k/v pairs
        - [ ] Determine if the note is worth action (TODO creation). If you resize the window during execution, everything crashes.
        How did the parameters get selected?
- [x] t_conesMosaicAbsorptionOISequenceEcc
       - [ ] Need to fill in the key/values section of the support function. Not sure if there are more possible k/v pairs
       - [ ] Check if I defined sigmaSeconds correctly in the support function generateTheOISequence, please.
- [x] t_conesMosaicHex1: 
      - [ ] mosaicParams comment says 16x16, but vector is 11 and 16?
      - [ ] lambda commented as 2 microns when defined as 3
- [x] t_conesMosaicHex2
      - [ ] mosaicParams comment says 16x16, but vector is 11 and 16?
- [x] t_conesMosaicHex6
      - [ ] TODO: Flesh out header more (I'm not sure my added description is correct!
      - [ ] TODO: Change output format to not constantly overwrite all of the existing figures (multiple subplots instead?)

**Comment by npcottaris** [comment]
1) t_conesPhotoPigment: Not sure what you are talking about. I don't see the issue
2)  t_conesMosaicHexReg: OK
3) t_conesMosaicHex: Fixed. Also improved visualizations.
4) t_conesMosaicAbsorptionEccBased. Crash happens because a video is generated and if you change the figure size the frame size changes. Now not generating video. 
5) t_conesMosaicAbsorptionOISequenceEcc. Removed. This tutorial demonstrates essentially the same thing with #4.
6) t_conesMosaicHex1. - no issues
7)  t_conesMosaicHex2. - no issues
8)  t_conesMosaicHex6 - Tutorial was obsolete. Deleted it.
