### ISSUE TITLE
opticsGet and Mysteriously large negative psf values (Marimont-Wandell)

### ISSUE THREAD

**Issue by tlian7** [isetbio/isetbio#380]
I've been running some code with the Marimont-Wandell model and got the "Mysteriously large negative psf values" error. I noticed in the comments that there's been some activity on this, and that there's the possibility to set a flag and turn the error into the warning (since MW OTF produces a PSF with negative values. )

However, I don't see a way to be able to pass that flag in if we're calling opticsGet(optics,'psf'), other than getting the OTF first and then running OtfToPsf.m

Does anyone have a less messy fix/idea for dealing with this?

**Comment by npcottaris** [comment]
The right solution is to add the `'warningInsteadOfErrorForNegativeValuedPSF'` as an optional argument in opticsGet() and then pass it to `OtfToPsf()`. 

I can do this, but let's hear from @DavidBrainard  and @wandell  first.

**Comment by DavidBrainard** [comment]
I believe I understand what is going on here.  It will take me longer to explain than I can write just now. The problem with the solution above is that one needs to special case how the PSF is obtained from the OTF for the M-W model, something I was trying hard to avoid.

Let me see if I can think of a better solution over the weekend.

**Comment by DavidBrainard** [comment]
I increased the default tolerance for negative psf values in OtfToPsf to 1% (from 0.1%).  I believe this fixes the M-W optics issue, although I have not run thorough tests yet.  I also think the M-W code is OK.  I am working on a tutorial that explains what the issue was, what the fix was, etc.

Closing this issue because I am an optimist.  But re-open if it is still broken.
