### ISSUE TITLE
Cone dark noise & eccentricity-based changes in cone quantal efficiency

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#383]
There are 2 issues here.

-  First, what should we recommend as the appropriate level of dark noise for cones?
-  Should we apply an eccentricity-based correction in the dark noise?

BTW, by default the dark noise is set to zero in the `coneMosaic` object, so all this discussion is related to situations where we want to include dark noise in the computations.

### Regarding the recommended dark noise level
A value of 300 R*/cone/sec was recommended by Fred Rieke in a personal correspondence with David Brainard. However, upon a literature search, I came upon the  Koenig & Hofer (2011)  "The absolute threshold of cone vision" paper, which summarizes estimates of dark noise from a number of studies. Table 5 from that paper is shown below.

![image 10-8-18 at 1 32 pm](https://user-images.githubusercontent.com/3444212/46624384-97146400-cafe-11e8-9082-720fb137cb57.jpg)

There is a large variability in the estimates of dark noise, but overall based on this Table, it seems that a recommended value of 300 R*/cone/sec might be too high. 

So, should we go with 100 R*/cone/sec estimate instead?

--------

### Regarding the correction in dark noise level with eccentricity
In out eccentricity-based hexagonal cone mosaics we correct the absorptions (which are computed for a foveal cone) based on the eccentricity-dependent variation in outer-segment length and inner segment diameter.

This correction is applied to the (dark noise + absorptions) signal. This would be OK, if we think that cones with longer outer segments and larger apertures have higher levels of dark noise, or in other words that the dark noise level should be proportional to the photopigment volume. More photopigment molecules -> more spontaneous isomerizations. The alternative is to apply the eccentricity-based corrections to the absorptions signal and then add the steady dark noise level.

What do people think?

----------

David Brainard thinks that the dark noise should be proportional to the number of photopigment molecules in the cone.  That is going to scale much, but not exactly like, the change in number of isomerizations.  The reason not exactly is the self-screening effect that applies to the absorptions but not to the number of photopigment molecules.  But correcting seems a little better than not correcting, and correcting differently just seems totally not worth it. David Brainard also makes the point that the uncertainty in the estimate of dark noise is going to completely dominate correcting or not for eccentricity.
 
I am leaving this issue open in case @fmrieke or someone else wants to comment.

**Comment by fmrieke** [comment]
A couple comments on this (none definitive unfortunately, but that reflects
our state of understanding):

- we have made direct measurements of noise in cones, mainly in the
periphery but also centrally.  Those indicate equivalent dark noise levels
of ~200 isomerizations/sec in L and M cones, and ~700 in S cones.  These
are much lower than previous physiological measurements, but still a bit
higher than the (indirect) measures from psychophysics.  There are lots of
possibilities for such discrepancies of course - starting with damage to
the cones in our in vitro preparations, and including errors introduced in
inferring noise from the psychophysics.  Yet they are not dramatically
different either - so that is good!
- noise in the cones appears to scale at most modestly with eccentricity -
effective noise levels and corresponding detection thresholds for the cones
are within a factor of two for the fovea, central retina and periphery
- cone noise does not appear to originate from the photopigment itself, but
instead downstream within the cone transduction cascade.
- S cones have slightly slower kinetics, and their kinetics change less
with background, than L and M cones.

Some of this is published, and some is getting there.  Happy to elaborate
on any of these too.

Best,
Fred

**Comment by npcottaris** [comment]
Added these notes in the compute() method of the @coneMosaic class.
