### ISSUE TITLE
Eye models

### ISSUE THREAD

**Issue by youtuyy** [isetbio/isetbio#387]
Hi, I have a question related to the three built-in eye models. Could you explain what these parameters mean in the writeNavarroLensFile.m file:
    % Columns are: radiusX, radiusY, thickness, materialIndex, semiDiameter,
    % conicConstantX, and conicConstantY
I am trying simulating a cornea with astigmatism with different refractive power along two perpendicular axes. I wonder if changing the conicConstant X and Y to be different will simulate this situation. 

Besides, for the Gullstrand mode, I wonder why there are conicConstant values. I am assuming that Gullstrand models to be paraxial models without aspherical surfaces. I might be wrong interpreting these parameters. It would be great if you could explain about them. Thank you!

**Comment by tlian7** [comment]
Hi @youtuyy,

In order to render through the eye, the ray-tracing program (PBRT) needs to take in these surface parameters to describe each surface. These parameters are based off the ones that are typically used in optical modeling software such as Zemax or CodeV. To explain each parameter:

- the radius X and radius Y correspond to the curvatures of the surface (curvature = 1/radius of sphere) in each direction
- the thickness is the distance in millimeters to the next surface (moving from the scene to the retina). The thickness of the last surface is set to zero because it is replaced with the retina distance, which is a settable parameter in the sceneEye class. 
- the material index is a number that tells the ray-tracing software which dispersion curve (index of refraction vs wavelength) to use for the material or media in between each surface. An index of X corresponds to the corresponding dispersion file `iorX__[accom].spd`. These are written out during `sceneEye.render` process and may also change depending on the eye model and accommodation settings.
- the semiDiameter is the height of the surface. You can think of it as the size of the surface. This parameter doesn't matter as much; it just needs to be big enough to capture rays passing through each surface but not too large as to overlap with other surfaces. 
- the conic constants describe the conicity of the surfaces. As you say, we can change the conicity in the X and Y direction, thereby creating a biocnic cornea and the effect of astigmatism. 

As for your point on the Gullstrand model: the lens file parameters are always fixed for the renderer, but depending on the model we might set the conicity to zero or keep the radius the same for both the X/Y direction. We figured that a more detailed lens prescription file was better, since we can always remove parameters by setting them to zero.

I hope this makes sense! I'm excited to hear that you are using the code for your analysis. I'd be interested to hear more of what you plan to use it for.

**Comment by youtuyy** [comment]
Thank you @tlian7 for your detailed and prompt answer! It helps a lot. 

Currently, I am trying to find an eye model (probably Arizona) suitable for simulating astigmatism and rendering its retinal images through ray tracing. I find your toolbox very helpful in that it can render retinal images and Arizona is built in. I might also try Zemax later. For now, this Matlab toolbox provides me with the function I need, and it's great I can also learn from the code. I would appreciate a lot if you have any suggestions about the simulation or there are other functionalities of the toolbox that might be related.

I am still planning the details about the next step with my project teammates. I will update here on how we plan to use it shortly.

**Comment by tlian7** [comment]
Looking forward to hearing more! Let me know if you have any more questions. In the meantime, I'll close this issue.
