### ISSUE TITLE
FAST validation still not perfect

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#4]
v_sceneRGB stopped working for Brian.  So at some point we need to figure this out.

**Comment by npcottaris** [comment]
This is really upsetting ...

Brian, when you get a chance, can you please do a 
* git pull
* run validateFastDebug(), and
* send me the command line output ?

Thank you,
Nicolas

**Comment by wandell** [comment]
Passed on my home computer (Macbook Pro).
[ 10] 'v_sceneFromRGB'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Fast validation      : PASSED against ground truth data of 06-Feb-2015 13:28:38.
	 > Ground truth info : wal-isc-video012.isc-video.upenn.edu / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :                         Macula / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	Data hash key        : abc8d0d6d7397cdd9bc6b988e94b4065eb79d83d5b71c54c69c1a239615061d6
	Validation report    : Hand check of h fov is within the specified tolerance (1e-12) of zero.

**Comment by npcottaris** [comment]
This is good, but still, we would like to know what causes the failure on that one computer. When you have a chance please run the debug script on the problematic computer and send me the output. 

It will take a few iterations to find the issue because it is not reproducible on our computers at Penn, but I think we should. Some user in the future may be unlucky and have one of those cursed computers :) 

Does Haomiao have access to that computer?

Thanks,
Nicolas

**Comment by wandell** [comment]
Should I still be getting this Exception on missing data from validateFastAll?
(The other failures on this computer are about ground truth data).

[  4] 'v_DisplayColorConversion'
	Internal validation  : FAILED
	Run-time status      : exception raised
	Validation report    : exception raised (and caught) with message: Calibration structure does not contain device colorimetric data

**Comment by npcottaris** [comment]
Hi Brian,

Yes, this runtime exception is expected on your computers because we have not yet migrated to ISETBIO a class for managing cal struct objects. I will do this tomorrow.

Thanks,
Nicolas

**Comment by DavidBrainard** [comment]
> On Apr 13, 2015, at 9:06 PM, Brian Wandell <notifications@github.com> wrote:
> 
> Should I still be getting this Exception on missing data from validateFastAll?
> (The other failures on this computer are about ground truth data).
> 
> [ 4] 'v_DisplayColorConversion'
> Internal validation : FAILED
> Run-time status : exception raised
> Validation report : exception raised (and caught) with message: Calibration structure does not contain device colorimetric data
> 
I thought I had fixed that error, but somehow I managed to remove the fix from my machine when I tried to push it up to the repositories.  The fix was actually in a routine in PTB.

I have now redone it and made sure it made its way both into the PTB repository and into the isetbio mirror of PTB routines it uses.

So, if you pull from isetbio the error should go away.  If it doesn’t, let me know.  My only theory then would be that you have PTB in front of isetbio on your path, but I doubt that you would do that.    If you do have PTB in front of isetbio, then either move it behind or update PTB from the gitHub master.

Sorry about this glitch.

**Comment by DavidBrainard** [comment]
Hi Nicolas,

Please don’t migrate that class.  We don’t need it for ISETBIO, and it will just be one more level of stuff to maintain if we put it in there

I have fixed this problem by making the relevant PTB routine forward compatible with the structure generated by our current calibration routines.  It was just a little glitch that the fix did not propagate.

DB

> On Apr 14, 2015, at 1:46 AM, Nicolas Cottaris <notifications@github.com> wrote:
> 
> Hi Brian,
> 
> Yes, this runtime exception is expected on your computers because we have not yet migrated to ISETBIO a class for managing cal struct objects. I will do this tomorrow.
> 
> Thanks,
> Nicolas
> 
> 
> > On Apr 13, 2015, at 9:06 PM, Brian Wandell <notifications@github.com> wrote:
> > 
> > Should I still be getting this Exception on missing data from validateFastAll?
> > (The other failures on this computer are about ground truth data).
> > 
> > [ 4] 'v_DisplayColorConversion'
> > Internal validation : FAILED
> > Run-time status : exception raised
> > Validation report : exception raised (and caught) with message: Calibration structure does not contain device colorimetric data
> > 
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/4#issuecomment-92550029>.
> > 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/4#issuecomment-92617836>.
> 


=========
David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by npcottaris** [comment]
Hi David,

This is still failing. The reason is that the Psychtoolbox version of SetSensorColorSpace is ahead of the ISETBIO version in our default path config.
It only works if
	addpath(genpath(isetbioRootPath), '-begin')
is executed before calling SetSensorColorSpace().

The reason it might be working for you is probably because you have the previous version of v_DisplayColorConversion.m in which
the removeBrainardLabPTBOverrides was buggy and did not remove all the overrides. Do a git pull on ISETBIO and rerun
v_DisplayColorConversion.m (in stand alone mode is fine), and you should get the Calibration structure does not contain device colorimetric data error.

We can fix this issue by changing our BrainardLabStartup script, but other users may  run into the same issue if their path has PTB ahead of ISETBIO.
This is not good. One solution would be to execute addpath(genpath(isetbioRootPath), '-begin') during s_initISET (after first saving the pre-existing path config)
and have another function, perhaps called s_shutdownISET, which each script should call, and which would reset the path to whatever it was before the call to s_initISET.

Nicolas

**Comment by DavidBrainard** [comment]
Belay the above comment from Nicolas.  We believe this is in fact working across systems.  We think it would only fail if you have a stale copy of PTB in front of ISETBIO on your path.

**Comment by wandell** [comment]
I just did a git pull on Psychtoolbox-3 and reran.  Alas

[  4] 'v_DisplayColorConversion'
	Internal validation  : FAILED
	Run-time status      : exception raised
	Validation report    : exception raised (and caught) with message: Calibration structure does not contain device colorimetric data

**Comment by npcottaris** [comment]
Brian,

Are you pulling PTB from 
    github.com/Psychtoolbox-3/Psychtoolbox-3.git 
or from 
   https://github.com/kleinerm/Psychtoolbox-3.git ?

The updated code is in the former url.

**Comment by wandell** [comment]
Not really sure how to tell, but I did this:

$git show origin
commit c93775e1614b2b42766145d8ed590d84b5e7d37d
Author: Mario Kleiner <mario.kleiner.de@gmail.com>
Date:   Wed Apr 8 18:27:39 2015 +0200

So, I guess I am pulling from the wrong repository.  Will try tonight and hope for a better response.

Some day you will have to tell me about all this.

**Comment by npcottaris** [comment]
Yes, this is Mario's dev version. It is he states:
This is the git repository for development of Psychtoolbox-3. Regular end users should stay away from it, unless instructed by us otherwise, and use our regular distribution system for production releases.

That's all I know. Perhaps David knows more :)

**Comment by DavidBrainard** [comment]
A) You want to be pulling from the repository at https://github.com/Psychtoolbox-3/Psychtoolbox-3.git.

B) The relevant routine is SetSensorColorSpace.  If the version you are running doesn't have a history comment from me today (4/14/15) then it isn't the right version.  The right version is available in isetbio/external/psychtoolbox/PsychCal as well as in the Psychtoolbox at the repospository above.

C) I just successfully made a useful image using lms2lmsDichromat.  Fun!

**Comment by wandell** [comment]
Amazing what a difference having the proper repository makes ;-).

Closing.
