### ISSUE TITLE
Ideas for outersegment class: Thursday skype meeting

### ISSUE THREAD

**Issue by jamesgolden1** [isetbio/isetbio#44]
We have a draft model of code for the outersegment class that I will put into a branch this evening. David and I had a brief discussion about the design of the class, and I've listed some notes from that below. We thought this could serve as a starting point for the Skype meeting on Thursday. 

a) are we happy with the set/get methods that call through set/get functions so that both, e.g., os.set and os=outersegSet(...) work?

b) constructor syntax - 
      1) should it do something by default with no arguments? 
              Like sensor, oi, scene
      2) what syntax for passing arguments to the constructor?
                        - key/value pair (always)
                        - defined optional arguments in fixed order
      3) what parameters do we want to be able to pass?
          for sure: calculation parameters

c) should the outersegment object store the sensor object?
      or should it extract the data it needs?
      1) how does this interact with handles or structs?
          if you store sensor, what if sensor is changed?

d) what is the structure and the syntax for handling different
calculation options? 
      1) use a structure for algorithm's parameters
      2) define a subclass for each version of the calculation
      3) define a computational object for each algorithm which
      encapsulates the parameters it needs and the algorithm but nothing
      else, and attach this to the outersegment object

**Comment by hjiang36** [comment]
Here's some of my personal thoughts:

a) I think we should have both and having one being just a wrapper and calling the other.
b) It's good to have constructors work without input arguments, meaning that having default values for all required parameters. Generally, I think we can have key-value pairs and accept parameters that are in os.set() method. Then, the constructors will be like
```  
  obj = OuterSeg(varargin)
      % Init all parameters to default values
      obj.name = 'default';
      % set user input
      for ii = 1 : 2 : length(varargin)
           obj.set(varargin{ii}, varargin{ii+1});
      end
  end
```
Surely, we should add some more input checks etc. Also, we can try to accept various input types for constructors, though MATLAB is not well-supported for that.

c) I prefer not to store sensor inside. I guess it only requires photon absorptions (maybe integration time? cone mosaic?). I prefer not to store these inside also. They can be input parameters to the compute function. We can also have an overloaded compute function that accept a sensor structure.

d) I like the second option. For the first one, different algorithms could use different parameter set and if all of them are put in the same class, it will be complicated and confusing (people will not know which parameter should be used / ignored when using certain algorithms). For the third one, the code structure is more complicated, and I don't see benefits over the second option.

Just my personal thought, let's have more discussions

**Comment by npcottaris** [comment]
Here are my thoughts.

a) I think we should choose one and stick with it. Having two versions, increases the code you have to write and maintain. I abide by the golden rule of programming: "The best line of code you will ever write is the one you do not write". Having two versions also increases the user's uncertainty, who might wonder if one way accomplishes something that the other one does not. I would choose 
~~~
os.variableName = os.variableValue;
~~~

b) Totally agree with Haomiao. Stick with optional key/value pairs and use a parser object to parse and validate the varargin.

c) Also agree with Haomiao. No need to store sensor inside, unless, you plan to change the sensor somehow. Eventually, when all isetbio structs get replaced by handle objects we should pass the appropriate handle.

d) I use the second option often. It is very clean. Collect all your common code in the parent class and declare abstract methods that will handle different versions of a computation in a subclass of the parent class. Finally make parent methods and properties needed by the subclass to be protected.

More later.
N.

**Comment by wandell** [comment]
Good agreement across the board so far on (b) and (c).  Count me in.

(a) ….
The issue of having a .set function or just setting the variable has pros and cons.  I liked using the xxxSet() originally because I changed variable names in the beginning and I didn’t have to find all the different sets in the code, but could just adjust xxxSet().  I also thought I would use aliases for the variable names in the code.  Finally, it gave me a place to try to put in comments and to be able to specify units as part of the xxxSet() call.

On the other hand, I can see N’s point as well.  At this point, I don’t rely on any of the features that were usefully in the early stages of code development.  In those days, the xxxSet was helpful, now not so much.

(d) …

Gotta go.  Not sure I have an opinion.  Sorry I will miss today’s Skype.

Brian

 
> On Jun 25, 2015, at 6:20 AM, Nicolas Cottaris <notifications@github.com> wrote:
> 
> Here are my thoughts.
> 
> a) I think we should choose one and stick with it. Having two versions, increases the code you have to write and maintain. I abide by the golden rule of programming: "The best line of code you will ever write is the one you do not write". Having two versions also increases the user's uncertainty, who might wonder if one way accomplishes something that the other one does not. I would choose
> 
> os.variableName = os.variableValue;
> b) Totally agree with Haomiao. Stick with optional key/value pairs and use a parser object to parse and validate the varargin.
> 
> c) Also agree with Haomiao. No need to store sensor inside, unless, you plan to change the sensor somehow. Eventually, when all isetbio structs get replaced by handle objects we should pass the appropriate handle.
> 
> d) I use the second option often. It is very clean. Collect all your common code in the parent class and declare abstract methods that will handle different versions of a computation in a subclass of the parent class. Finally make parent methods and properties needed by the subclass to be protected.
> 
> More later.
> N.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/44#issuecomment-115255605>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by DavidBrainard** [comment]
I tend to think we want the syntax os.set and os.get(...).

One possible syntax is that the set function works as: os.set('theImportantParameter',itsValue,....) while the get function works as os.get('theImportantParameter',....). 

In both cases, .... stands for optional key value pairs, such as 'Units','mm') or whatever else might be needed to modify the basic input.

The reason for wanting a get function is because not all things we want to get from objects exist in stored format, and thus need to be computed on the fly.  This means that simply using the os.theImportantValue to access won't always work.  And once we need a get for one thing, I think stylistic consistency dictates using it for everything.

That then suggests that similarly, we ought to have set functions for everything.  There will probably times when we want to do things like specify units and I like the idea of doing it all as key value pairs.

I have not done much object coding in Matlab, though, so perhaps I am missing things it makes easy to do that would suggest a different syntax.

If there is some easy way that we can make an object reveal what sets and gets are implemented, and what the syntax available for each is, that would be great.  So, if I know I want to get 'theImportantParameter', it would be nice to have an easy way to find out what optional key value pairs could be used in conjunction with it.  This may be hard to do, though.

**Comment by jamesgolden1** [comment]
Thank you all for the input - Nicolas has written some code implementing subclasses for the different computation methods. I will incorporate this framework into the current outersegment branch, as well as implement initialization with default properties and the appropriate methods for using os.set and os.get.

I'll mark this issue closed.
