### ISSUE TITLE
coneAdapt missing

### ISSUE THREAD

**Issue by hjiang36** [isetbio/isetbio#79]
I found that coneAdapt function is removed in commit 8a2d6505d6fca3cbbf26c239aca25aef641e1b62.
Shall I call riekeAdapt and riekeAddNoise directly?

**Comment by DavidBrainard** [comment]
It was in a deprecated directory and I got rid of that before the workshop because Brian and I thought “deprecated” would not look so good to browsers.

What we should really do is take the time to switch over to the outer segement object.  

That is, let’s not write any more code that we will have to modify very soon, unless there is a desparate immediate need for it.

**Comment by jamesgolden1** [comment]
I think the outer segment object is close to being ready. David, maybe some time this week you and I could Skype and discuss?
