### ISSUE TITLE
wavefront to oi

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#90]
After clearing the idea with David B. today, I made a change to the wvf2oi function.  Rather than converting from the wavefront structure based on the psf data, we now convert based on the OTF data.

All the wvf validation tests still pass, but I these mainly test the wvf code itself, which I didn't change. They do use wvf2oi a bit, and nothing seemed broken;  Also, the graphs I made to check are qualitatively the same as they ever were.  I will try to write a unit test for the new wvf2oi function.

Still, this was a significant computational change and it made me nervous.  So, I am posting here to hope that everyone keeps an eye out for any problems that I might have created with this change.  If it shows up anywhere for you, it would be any scripts that call oiCreate('wvf human').

**Comment by jamesgolden1** [comment]
Brian, from your comments in wvf2oi.m it seems the problem was with fftshift and the placement of the DC term as used by the siSynthetic function. Should other files that call fft2 and fftshift with the PSF be changed to use circshift instead of fftshift? I noticed those commands are also called in wvfComputePSF. It seems this would affect a few of the tutorial and validation functions.

**Comment by DavidBrainard** [comment]
I would proceed with a little care here.  The wavefront code as is does a good job reproducing the diffraction limited PSF, so it isn’t too broken.  It is possible I did something like enforce an odd number of pixels so that fftshift did the expected thing.  I am not sure.  Indeed, I have never used circshift and always thought I understood what fftshift did.  But it would be worth making sure that the wavefront code is working right — these fft arg things are always tricky and it is possible something is indeed out of whack.

DB

> On Nov 10, 2015, at 1:47 PM, jamesgolden1 <notifications@github.com> wrote:
> 
> Brian, from your comments in wvf2oi.m it seems the problem was with fftshift and the placement of the DC term as used by the siSynthetic function. Should other files that call fft2 and fftshift with the PSF be changed to use circshift instead of fftshift? I noticed those commands are also called in wvfComputePSF. It seems this would affect a few of the tutorial and validation functions.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/90#issuecomment-155528012>.
> 

David H. Brainard
Professor of Psychology
Director, Penn Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by wandell** [comment]
Right.  Let's leave the other stuff alone.  The was really moving between the shift-invariant representation in ISET/ISETBIO and the WVF Toolbox.  The numbers within each domain match up.  So the fftshift/circshift was really just about moving between the two domains.

Onward!
