### ISSUE TITLE
Validation hooks

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#95]
As I come back to programming after the semester of teaching dangerously, I am discovering that many validation scripts fail.  Most don't fail much, just small numerical differences here and there.  I am going through the scripts, convincing myself that the failures aren't the result of anything particularly bad, and regenerating the ground truth data.  I conjecture that the failures are due to things like some small tweak in defaults for human sensor, and stuff like that.  But it has been long enough since whatever edit caused the change that tracking each one down in detail seems impossible.

As we move forward, I think we want to try to set up some sort of validation hook where we run through all validations somewhere in the background on each commit, so we know right away when something changes a validation.  Or maybe not per commit but on a schedule.  Ben (as well as Jeremy Freeman) have told me that this is now fairly straightforward to set up in the cloud, so that it runs in the background and just emails a useful notification.

**Comment by benjamin-heasly** [comment]
While merging a recent pull request, Github notified me about these very hooks.  Here are several tools that GitHub knows how to hook into:
  https://github.com/integrations/feature/code

So I agree setting up the hooks should be easy.

Setting up a Matlab-enabled server to run our validations would be a little more tricky.  Instead of using a free, handy server provided by one of the tools above, I think we wil need to host our own build server and give it access to our Matlab license server.  I think we can to this.  But it will take a little effort.

**Comment by benjamin-heasly** [comment]
#### Begin Sales Pitch

The jargon for what I think we want is [Continuous Integration aka CI](https://en.wikipedia.org/wiki/Continuous_integration).  At a minimum, CI would be commit hooks and a server that run our validations automatically when we push to GitHub.

CI could also be a development practice (aka Kool Aid) that we adopt if we want.  It would be easy to overthink this.  But one workflow that I like goes like this:
 * Always make changes in a short-lived git branch.
 * When ready, push the branch to GitHub and make a pull request.
 * Let the hooks fire and validations run on the pull request.  GitHub will report "pass" or "fail" right in the pull request page.
 * Let someone else look at / grok / critique the pull request.
 * Finally, use the button on the GitHub pull request page to merge the branch into the master branch.

This helps the master branch stay healthy.  It also encourages sharing of changes/knowledge with the group.

Personally, it also helps me focus on one problem at a time because I know in the back of my head "Someone's going to read this pull request".  Chances are, someone's going to encounter the changes anyway, so why not give it to them in a nice, bite-sized pull request?

#### End of Sales Pitch

**Comment by DavidBrainard** [comment]
Closing.  We need to get Jenkins to email us again, when validations fail.  But other than that I think we are doing OK.  Perhaps we should be doing more PR's and less pushing, but I think we've sort of reached equilibrium and don't need an issue anymore.
